- common/changes/@azure-tools/typespec-client-generator-core/additional_properties_2023-12-13-06-56.json
- packages/typespec-client-generator-core/doc/types.tsp
- packages/typespec-client-generator-core/src/interfaces.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/types.test.ts
Fix https://github.com/Azure/typespec-azure/issues/17
> Add type info for additional properties in model type

- common/changes/@azure-tools/typespec-client-generator-core/tcgc-flatten-property_2024-01-08-09-09.json
- docs/libraries/typespec-client-generator-core/reference/decorators.md
- docs/libraries/typespec-client-generator-core/reference/index.mdx
- packages/typespec-client-generator-core/README.md
- packages/typespec-client-generator-core/lib/decorators.tsp
- packages/typespec-client-generator-core/src/decorators.ts
- packages/typespec-client-generator-core/test/decorators.test.ts
- implement `@flattenProperty`
- implement `shouldFlattenProperty` utility function
- add test cases
resolve #13
> feat(decorator): add `@flattenProperty`

- common/changes/@azure-tools/typespec-client-generator-core/tcgc-remove_dynamic_2024-01-08-22-20.json
- packages/typespec-client-generator-core/test/decorators.test.ts
The vitest extension in VSCode does not support dynamic testing in test files. If there are any dynamic tests, individually running any test with the extension will fail with error `TypeError: Cannot read properties of undefined, reading 'item'`.
> [tcgc] remove dynamic to support vitest extension

- eng/feeds/arm/tspconfig.yaml
It looks like this was not successfully backmerged from the release branch
> Add read-only to ARM status enums

- common/changes/@azure-tools/typespec-autorest/fix-autorest-decimal128_2024-01-29-21-10.json
- packages/typespec-autorest/src/openapi.ts
- packages/typespec-autorest/test/primitive-types.test.ts
`decimal128` might be the correct format as established in the registry but autorest doesn't support it today and treats `decimal` as a 128bit decimal
> HotFix: Autorest emitter should generated format: decimal

- .chronus/changes/fix-missing-x-ms-id-rule-2024-1-23-17-39-50.md
- packages/typespec-azure-resource-manager/src/rules/missing-x-ms-identifiers.ts
Issue was I wrote this rule by copying `no-enum` rule but forgot to remove the diagnostic report on every enum.
> Fix `missing-x-ms-identifiers` rule triggering for every `enum`

- .chronus/changes/fix_usage_for_additional_properties-2024-1-23-18-7-29.md
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/types.test.ts
Fix: https://github.com/Azure/typespec-azure/issues/153
> Add usage calculation for additional properties with model type

- .chronus/changes/add_operation_status-2024-1-23-16-6-53.md
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/public-utils.test.ts
> Add operation status

- .chronus/changes/error_models-2024-1-27-16-15-52.md
- packages/typespec-client-generator-core/src/interfaces.ts
- packages/typespec-client-generator-core/src/public-utils.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/types.test.ts
Recursively check if a model is an error model bc [questions](https://github.com/microsoft/typespec/issues/2957) about whether typespec's `isErrorModel` should recursively check needs to have a design review
> [tcgc] recursively check error models

- .chronus/changes/fix_union_variant-2024-1-28-18-32-18.md
- packages/typespec-client-generator-core/src/interfaces.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/public-utils.test.ts
- packages/typespec-client-generator-core/test/types.test.ts
fix: https://github.com/Azure/typespec-azure/issues/326
> Fix union as enum issues

- .chronus/changes/flatten-2024-1-20-11-30-53.md
- packages/typespec-autorest/src/openapi.ts
- packages/typespec-autorest/test/flatten.test.ts
resolve: https://github.com/Azure/typespec-azure/issues/276
> Support new added `@flattenProperty` decorator in autorest emitter

- .chronus/changes/use_own_usage_flags-2024-2-8-16-57-50.md
- packages/typespec-client-generator-core/src/decorators.ts
- packages/typespec-client-generator-core/src/interfaces.ts
- packages/typespec-client-generator-core/src/package.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/types.test.ts
I've verified that this code still works, so language emitters currently relying on `typespec/compiler`'s `UsageFlags` won't be broken
```typescript
import { UsageFlags } from "@typespec/compiler";
import { getAllModels } from "@azure-tools/typespec-client-generator-core";
const models = getAllModels(sdkContext).filter(x => x.usage === UsageFlags.Input);
```
> [tcgc] Use own usage flags

- .chronus/changes/cached-operation-2024-2-11-17-52-48.md
- packages/typespec-client-generator-core/src/internal-utils.ts
- packages/typespec-client-generator-core/src/package.ts
- packages/typespec-client-generator-core/src/public-utils.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/public-utils.test.ts
resolve: https://github.com/Azure/typespec-azure/issues/394
> add a cached `getHttpOperation` helper function

- .chronus/changes/prevent-carry-over-2024-2-13-14-34-30.md
- packages/typespec-client-generator-core/src/decorators.ts
- packages/typespec-client-generator-core/test/decorators.test.ts
resolve: https://github.com/Azure/typespec-azure/issues/233
> prevent carry over for `@clientName`

- .chronus/changes/template-name-2024-2-11-16-30-13.md
- packages/typespec-client-generator-core/src/public-utils.ts
- packages/typespec-client-generator-core/test/public-utils.test.ts
- packages/typespec-client-generator-core/test/types.test.ts
resolve: https://github.com/Azure/typespec-azure/issues/334
> give a nonredundant name for templated instance model

- eng/pipelines/jobs/build-and-test.yml
The task running tests already fails if tests have failed:
So the task publishing the test results failing makes a wrong impression that it failed to upload the test results, what's not the case.
> Set failTaskOnFailedTests=false in CI pipeline

- .chronus/changes/discriminator_sequence-2024-2-20-15-38-34.md
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/types.test.ts
```
@discriminator("kind")
model Foo {
name: string
}
```
Previous behavior: properties as ["name", "kind"].
Change to: properties as ["kind", "name"].
> Adjust generated discriminator property sequence to prevent potential breaking change

- .chronus/changes/response_structure-2024-2-25-17-16-10.md
- packages/typespec-client-generator-core/src/interfaces.ts
- packages/typespec-client-generator-core/src/internal-utils.ts
- packages/typespec-client-generator-core/src/package.ts
- packages/typespec-client-generator-core/test/package.test.ts
The `HttpOperationResponse` that `@typespec/http` returns to us has property `.statusCodes` on each of them. The type of this is `HttpStatusCodeRange | number | "*"`. On the tcgc side, we're creating a map to more easily map status codes to the expected responses. We used to map this as a `Record` of `number | string` (we would do some processing magic for status codes). However, we've decided to switch to a `Map` since it can handle complex key inputs, and made the key inputs the same as the `.statusCodes` type from `tsp` for fidelity.
All instances of passing the responses to `Object.keys(responses)` / `Object.values(responses)` / `Object.items(responses)` should be changed, and you can directly access the native `.keys(responses)` etc
> [tcgc] change response structure to mapping with key number, status code range, or *

- .chronus/changes/rename_initial_operation-2024-2-27-14-56-44.md
- packages/typespec-client-generator-core/src/interfaces.ts
- packages/typespec-client-generator-core/src/package.ts
This avoids duplicate `.operation` and `.initialOperation` on `SdkLroMethod`
> [tcgc] rename lroMethod.initialOperation -> lroMethod.operation

- packages/website/package.json
- pnpm-lock.yaml
Gets into a race condition and website tries to gen the docs for the package before it is build
> Fix website build due to missing dependency on new autorest-canonical package

- .github/ISSUE_TEMPLATE/bug-report.yml
The previous URL returns a 404
> Fix TypeSpec playground url in bug report template

- .chronus/changes/604-2024-3-5-16-44-59.md
- docs/libraries/azure-resource-manager/rules/missing-x-ms-identifiers.md
- packages/typespec-azure-resource-manager/src/rules/missing-x-ms-identifiers.ts
- packages/typespec-azure-resource-manager/test/rules/missing-x-ms-identifiers.test.ts
- packages/website/versioned_docs/version-latest/libraries/azure-resource-manager/rules/missing-x-ms-identifiers.md
Fixes #604 and also resolves a syntax error in the documentation for `missing-x-ms-identifiers`.
> Specify the fully qualified name of `@OpenAPI.extension` decorator in `missing-x-ms-identifiers` linter warning

- .chronus/changes/fix_access-2024-3-10-18-31-10.md
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/decorators.test.ts
found with latest stable version when regenerating openai.
the root cause is wrong calculation for operation model map.
we should only calculate it once after model build finish.
> fix wrong propagation for nullable properties

- .chronus/changes/fix-missing-body-root-2024-3-19-13-3-12.md
- packages/typespec-azure-resource-manager/lib/operations.tsp
Missed in some templates and it is making some spec fail in spec repo
> Fix missing `@bodyRoot`

- docs/howtos/DataPlane Generation - DPG/08methodInputs.mdx
fixes https://github.com/Azure/autorest.typescript/issues/2413
as title, to add spread alias doc for js rlc and modular.
> add-spread-alias-doc-for-js

- docs/howtos/DataPlane Generation - DPG/08methodInputs.mdx
Adding a caution section about the spread / anonymous model.
It is not always best to do this spread, as it affect SDK signature. For some languages, having lots of method arguments is not a good design.
---
.NET and Java have guideline on "simple methods" that should not have more than 6 arguments.
Python and TypeScript/JavaScript does not have such guideline (AFAIK). Python has keyword argument. TypeScript does not put optional arguments to method.
Since here the pattern applies to all languages, I am trying to adopt a stricter advice.
> dpg doc, add caution section to spread doc

- .chronus/changes/union_null-2024-3-23-17-23-22.md
- packages/typespec-client-generator-core/src/public-utils.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/types.test.ts
fix: https://github.com/Azure/typespec-azure/issues/725
> [tcgc] fix additional property union naming problem

- .chronus/changes/rules-addEnumDocExceptions-2024-3-19-22-29-42.md
- packages/typespec-azure-core/src/rules/require-docs.ts
- packages/typespec-azure-core/test/rules/require-docs.test.ts
Closes https://github.com/Azure/typespec-azure-pr/issues/3107
After merging, I will make a PR to clean up the suppressions in the REST API specs repo.
> [Core] Exempt versioning enums and discriminator enum/unions from documentation required rule

- .chronus/changes/tsp-unionDocs-2024-3-25-19-26-44.md
- packages/typespec-azure-core/src/rules/require-docs.ts
- packages/typespec-azure-core/test/rules/require-docs.test.ts
Closes #516 .
This PR:
- Exempts discriminator unions from requiring documentation
- Requires documentation of the union itself
- Requires documentation of named union variants, but not symbolic variants
**REST API Specs**
Violations: 27
https://github.com/Azure/azure-rest-api-specs/pull/28849
> Require documentation of unions

- .chronus/changes/core-fixRpcOperationRequestBodyRule-2024-3-29-20-4-13.md
- packages/typespec-azure-core/src/rules/rpc-operation-request-body.ts
- packages/typespec-azure-core/test/rules/rpc-operation-request-body.test.ts
Turns out this rule was never actually looking for a request body at all. It only cared if you were using the RpcOperation tempalte with `@get` or `@delete`!
Fixes #684.
> Core: Fix `rpc-operation-request-body` rule

- .chronus/changes/fix_client_version_params-2024-4-3-14-57-7.md
- packages/typespec-client-generator-core/src/decorators.ts
- packages/typespec-client-generator-core/src/http.ts
- packages/typespec-client-generator-core/src/internal-utils.ts
- packages/typespec-client-generator-core/src/package.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/decorators.test.ts
Right now, we have all api version information tied to the `sdkContext` as a whole. As an example, this means that when we add a client in a later version, we're not able to have granular handling of api version for the second client.
In this PR, I've made all api version information a mapping from namespace to apiVersion information. I also added a test that reproduces one of the previous issues.
The PR diff is large bc I've had to add parameters everywhere so I'm still passing
> Fix client version params

- .github/policies/issues.inactivity.yml
- .github/policies/issues.triage.yml
That flow has been present in microsof/typespec for a while. It will automatically comment and close on issues without reply from author when marked with needs-author-feedback
> Inactivity triage

- packages/website/docusaurus.config.ts
Not redering the release notes with `diff` correctly . We already have that in typespec core
> Add diff highlighting to website

- .chronus/changes/fix_void-2024-4-8-13-39-22.md
- packages/typespec-client-generator-core/src/http.ts
- packages/typespec-client-generator-core/src/internal-utils.ts
- packages/typespec-client-generator-core/src/package.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/package.test.ts
- packages/typespec-client-generator-core/test/types.test.ts
resolve: https://github.com/Azure/typespec-azure/issues/795
> [tcgc] add void and never handling for parameter and return types

- .chronus/changes/add_naming_constant-2024-3-30-17-2-35.md
- packages/typespec-client-generator-core/src/http.ts
- packages/typespec-client-generator-core/src/interfaces.ts
- packages/typespec-client-generator-core/src/internal-utils.ts
- packages/typespec-client-generator-core/src/public-utils.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/types.test.ts
> [tcgc] add generated names for constants

- .chronus/changes/propogate_api_version-2024-4-9-17-53-45.md
- packages/typespec-client-generator-core/src/decorators.ts
- packages/typespec-client-generator-core/src/http.ts
- packages/typespec-client-generator-core/src/internal-utils.ts
- packages/typespec-client-generator-core/src/package.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/package.test.ts
- packages/typespec-client-generator-core/test/test-host.ts
> Propogate api version

- .chronus/changes/fix-omitted-non-version-enums-2024-4-15-8-39-12.md
- packages/typespec-autorest/src/openapi.ts
- packages/typespec-autorest/test/options.test.ts
fix #838
The `isVersionEnum` function was just completely wrong and just returned true for any enum when used in a versioned spec.
> Do not omit unreferenced non version enum when `omit-unreachable-types` is not set to true

- .chronus/changes/fix-non-breaking-versioning-2024-4-22-14-2-44.md
- packages/typespec-azure-rulesets/src/rulesets/resource-manager.ts
Wrongly removed from both ruleset previously but the previous behavior of `typespec-resource-manager/all` was to have it included.
> Fix `@azure-tools/typespec-azure-core/non-breaking-versioning` should actually be part of resource-manger

- .chronus/changes/fix-non-breaking-versioning-2024-4-22-14-2-44.md
- .github/workflows/consistency.yml
- packages/typespec-azure-rulesets/src/rulesets/resource-manager.ts
Reverts Azure/typespec-azure#906
Rule wasn’t actually enabled in the ruleset extended so this was correct before
> Revert "Fix `@azure-tools/typespec-azure-core/non-breaking-versioning` should actually be part of resource-manger"

- .chronus/changes/fix-emit-api-version-2024-4-25-9-53-10.md
- packages/samples/test/output/core/versioning/@azure-tools/typespec-autorest/v1/openapi.json
- packages/samples/test/output/core/versioning/@azure-tools/typespec-autorest/v2/openapi.json
- packages/typespec-autorest/src/openapi.ts
- packages/typespec-autorest/test/versioning.test.ts
This ensure that when the version enum is still referenced that 
1. we still mark it as modelAsString true to not be flagged as a breaking change in spec repo(even though it won't matter as it gets special treatment)
2. only include the emitted version member so adding new versions in the future don't update the previous one
> Fix when rendering version enum only include current member and mark it modelAsString: true

- .chronus/changes/default_access_public-2024-4-28-12-23-9.md
- docs/howtos/DataPlane Generation - DPG/03convenient.mdx
- docs/howtos/DataPlane Generation - DPG/07tcgcTypes.mdx
- packages/typespec-client-generator-core/src/decorators.ts
- packages/typespec-client-generator-core/src/interfaces.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/decorators.test.ts
- packages/typespec-client-generator-core/test/types.test.ts
fixes https://github.com/Azure/typespec-azure/issues/926
> [tcgc] default `.access` to `"public"`

- .chronus/changes/emitter_name-2024-5-3-22-57-49.md
- packages/typespec-client-generator-core/src/internal-utils.ts
- packages/typespec-client-generator-core/test/internal-utils.test.ts
resolve: https://github.com/Azure/typespec-azure/issues/937
> [tcgc] support new typespec emitter naming rule

- .chronus/changes/fix_core_model_filter-2024-5-6-15-47-3.md
- packages/typespec-client-generator-core/src/internal-utils.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/public-utils.test.ts
previous logic has two problems:
1. it could not handle any models found in model properties, union variants and so on
2. it will include some of the model used in templated model but not used in real operation
new logic:
1. do not do any filtering when traversal
2. do the filtering at final stage of `getAllModels`
3. set usage to `None` to filter out model not used
> [tcgc] refine logic of core model filtering

- .chronus/changes/autorest-emitt-all-programmatically-2024-5-7-9-28-38.md
- packages/typespec-autorest/src/emit.ts
- packages/typespec-autorest/src/index.ts
- packages/typespec-autorest/src/openapi.ts
- packages/typespec-autorest/src/types.ts
Expose an API like we have in openapi3 emitter to emit all services at all version programmatically
> Autorest emit all files programatically

- .chronus/changes/client_hierarchy-2024-5-18-18-19-30.md
- packages/typespec-client-generator-core/src/interfaces.ts
- packages/typespec-client-generator-core/src/package.ts
- packages/typespec-client-generator-core/test/decorators.test.ts
- packages/typespec-client-generator-core/test/package.test.ts
- packages/typespec-client-generator-core/test/types/multipart-types.test.ts
resolve: https://github.com/Azure/typespec-azure/issues/1040
> [tcgc] only expose top level client in SdkPackage

- .chronus/changes/override_with_detailed_access-2024-5-18-18-9-31.md
- packages/typespec-client-generator-core/src/decorators.ts
- packages/typespec-client-generator-core/test/decorators.test.ts
> [tcgc] allow csv list of scopes

- .chronus/changes/whitespace_client_name-2024-5-24-14-18-45.md
- packages/typespec-client-generator-core/src/decorators.ts
- packages/typespec-client-generator-core/src/lib.ts
- packages/typespec-client-generator-core/test/decorators.test.ts
> [tcgc] add linter for empty client names

- .chronus/changes/remove_name_in_client-2024-5-24-13-45-6.md
- packages/typespec-client-generator-core/src/http.ts
- packages/typespec-client-generator-core/src/interfaces.ts
- packages/typespec-client-generator-core/src/package.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/package.test.ts
- packages/typespec-client-generator-core/test/types/body-model-property-types.test.ts
- packages/typespec-client-generator-core/test/types/model-types.test.ts
> [tcgc] remove deprecated `nameInClient` property from `SdkModelPropertyType`s

- .chronus/changes/remove_is_error_child_of_error-2024-5-24-15-29-24.md
- packages/typespec-client-generator-core/src/public-utils.ts
Right after we added this function, `isErrorModel` from `@typespec/compiler` would check inheritance for error. I've checked and no one uses this. Since it was never used, I'm going to go ahead and remove it
> remove unused isErrorOrChildOfError

- .chronus/changes/rename_datetime_type-2024-5-24-14-52-19.md
- packages/typespec-client-generator-core/doc/types.tsp
- packages/typespec-client-generator-core/src/interfaces.ts
- packages/typespec-client-generator-core/src/types.ts
> [tcgc] unify datetime casing by renaming interface types

- .chronus/changes/fix_decorator_list-2024-5-26-13-53-0.md
- packages/typespec-client-generator-core/src/configs.ts
- packages/typespec-client-generator-core/src/http.ts
- packages/typespec-client-generator-core/src/interfaces.ts
- packages/typespec-client-generator-core/src/internal-utils.ts
- packages/typespec-client-generator-core/src/package.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/types/general-decorators-list.test.ts
fix for https://github.com/Azure/typespec-azure/pull/966
> [tcgc] change generic decorator list data structure to support duplicate decorator use case

- .chronus/changes/fix-managed-identity-def-issue-2024-6-2-18-48-2.md
- docs/libraries/azure-resource-manager/reference/data-types.md
- packages/typespec-azure-resource-manager/lib/common-types/managed-identity.tsp
fixes https://github.com/Azure/typespec-azure/issues/1110
to match with the swagger definition https://github.com/Azure/azure-rest-api-specs/blob/87a08b955c257c773a3bd42553c718d4b1092955/specification/common-types/resource-management/v5/managedidentity.json#L9-L16
> Fix [Bug]: Wrong `null` tagging in ManagedServiceIdentity

- eng/pipelines/templates/1es-redirect.yml
From Azure sdk for js repo >
> All the other languages have disabled codeql and we are now hitting blocking issues when running codeql on macos (https://dev.azure.com/twcdot/Data/_workitems/edit/138580) and even on the other OS's the configuration causes the builds to run for a long time.
https://github.com/Azure/azure-sdk-for-js/pull/30277
> Disable 1ds codeql

- .chronus/changes/fix_naming_issue-2024-6-12-17-6-31.md
- packages/typespec-client-generator-core/src/public-utils.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/public-utils.test.ts
fix: https://github.com/Azure/typespec-azure/issues/1150
cc: @ArcturusZhang  @archerzz
> [tcgc] `findContextPath` need to handle nested operation group, also refine the logic for naming and composing cross language definition id

- docs/howtos/migrate-swagger/migrate-dp-tips.md
Adding a migration guide to provide information that is usually helpful when migrating specs from swagger to typespec after running them through the converter.
> Add migration guide for data-plane specs converting from swagger to typespec

- .chronus/changes/azhang_ARMPropertiesOptional-2024-6-12-15-49-5.md
- docs/libraries/azure-resource-manager/reference/data-types.md
- packages/typespec-azure-resource-manager/lib/models.tsp
- packages/typespec-azure-resource-manager/lib/private.decorators.tsp
- packages/typespec-azure-resource-manager/src/private.decorators.ts
- packages/typespec-azure-resource-manager/test/resource.test.ts
Added an optional template parameter on `TrackedResource`, `ProxyResource`, and `ExtensionResource` ARM templates that allows brownfield services to customize the optionality of the ARM resource `properties` field.
Closes #131
> Optional template parameter to customize the optionality of ARM resource `properties` field

- .chronus/changes/timotheeguerin-patch-1-2024-6-10-15-45-54.md
- packages/typespec-azure-resource-manager/src/rules/utils.ts
Used in linter rules that expect alphanumeric chars or dash starting with lowercase letter so this seems like the correct regex
> Fix codeql warning on regex

- .chronus/changes/azure-core-dec-signatures-2024-6-18-17-49-0.md
- docs/libraries/azure-core/reference/decorators.md
- packages/typespec-azure-core/README.md
- packages/typespec-azure-core/generated-defs/Azure.Core.Foundations.Private.ts
- packages/typespec-azure-core/generated-defs/Azure.Core.Foundations.ts
- packages/typespec-azure-core/generated-defs/Azure.Core.Foundations.ts-test.ts
- packages/typespec-azure-core/generated-defs/Azure.Core.Traits.Private.ts
- packages/typespec-azure-core/generated-defs/Azure.Core.Traits.ts
- packages/typespec-azure-core/generated-defs/Azure.Core.Traits.ts-test.ts
- packages/typespec-azure-core/generated-defs/Azure.Core.ts
- packages/typespec-azure-core/generated-defs/Azure.Core.ts-test.ts
- packages/typespec-azure-core/lib/traits.tsp
- packages/typespec-azure-core/package.json
- packages/typespec-azure-core/src/decorators.ts
- packages/typespec-azure-core/src/lib.ts
- packages/typespec-azure-core/src/traits.ts
- packages/typespec-azure-core/tsconfig.json
Step to having all our libraries use tspd to generate the signatures and make sure they are in sync.
There is quite a lot of times we expected the wrong type which would cause a crash. This fix a few to get the more precise type in the TypeSpec if it was going to crash originally. Otherwise expand the type in the TS
> Migrate azure core library to use generated decorator signature

- .chronus/changes/xml_usage-2024-6-19-15-33-55.md
- packages/typespec-client-generator-core/src/interfaces.ts
- packages/typespec-client-generator-core/src/internal-utils.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/types/general-decorators-list.test.ts
- packages/typespec-client-generator-core/test/types/model-types.test.ts
> [tcgc] add xml usage and fix generic decorator issue

- .chronus/changes/operation-validation-2024-6-19-18-35-46.md
- packages/typespec-client-generator-core/src/validate.ts
- packages/typespec-client-generator-core/test/decorators.test.ts
Fix operation client name validation introduced in https://github.com/Azure/typespec-azure/pull/1119
> fix `@clientName` validation for operation within interface

- .chronus/changes/operation-validation-2024-6-19-18-35-46.md
- packages/typespec-client-generator-core/src/validate.ts
- packages/typespec-client-generator-core/test/decorators.test.ts
Fix operation client name validation introduced in https://github.com/Azure/typespec-azure/pull/1119
> fix `@clientName` validation for operation within interface (#1205)

- .chronus/changes/multipart-array-update-2024-6-29-12-50-4.md
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/types/multipart-types.test.ts
After discussion with language devs, for `HttpPart<T>[]`, TCGC changes type from:
```
{
"kind: "model"
"multipartOptions": {"isMulti": true}
}
```
to 
```
{
"kind: "array",
"valueType": {"kind": "model"},
"multipartOptions": {"isMulti": true}
}
```
> [TCGC][Multipart] Change output for `HttpPart<T>[]`

- .chronus/changes/cut-off-base-on-std-type-2024-6-29-16-44-37.md
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/types/built-in-types.test.ts
- packages/typespec-client-generator-core/test/types/date-time-types.test.ts
- packages/typespec-client-generator-core/test/types/duration-type.test.ts
In previous version, the base type on `SdkBuiltInType` will give you every details on those std type, you could even see:
```
int32 -> int64 -> integer -> numeric
```
This is completely redundant.
This PR cuts off those redundant base type calculation once we know that the current type is a std type.
Also adds a few new test cases to test those very basic types.
> cut off the base type calculation when this type is a std type

- .chronus/changes/refactor-autorest-parameter-resolution-2024-6-26-16-6-16.md
- packages/samples/test/output/core/optional/@azure-tools/typespec-autorest/openapi.json
- packages/typespec-autorest/src/openapi.ts
- packages/typespec-autorest/src/openapi2-document.ts
- packages/typespec-autorest/test/parameters.test.ts
When making the URI template PR it was a bit hard to deal with the mess and better to split the refactoring
Also fix issue where `multi` wasn't even allowed for header part https://github.com/Azure/typespec-azure-pr/issues/3825
> Refactor parameter handling in swagger emitter

- .chronus/changes/fix-canonical-included-versions-2024-7-31-11-30-47.md
- packages/typespec-autorest-canonical/src/emitter.ts
- packages/typespec-autorest-canonical/test/versioning.test.ts
Fix the included versions value in canonical emitter. 
It returned the version name, should return version value instead. Updated the test case.
> [Canonical Emitter] Fix included versions value in canonical emitter

- .chronus/changes/endpoint_client_default-2024-6-30-14-27-25.md
- packages/typespec-client-generator-core/src/package.ts
- packages/typespec-client-generator-core/test/package.test.ts
> [tcgc] add clientDefaultValue for endpoint template arguments

- .chronus/changes/multipart-bodyparam-fix-2024-2024-7-1-15-10-38.md
- packages/typespec-client-generator-core/src/decorators.ts
- packages/typespec-client-generator-core/src/http.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/package.test.ts
- packages/typespec-client-generator-core/test/types/model-types.test.ts
supplement for PR https://github.com/Azure/typespec-azure/pull/1090
- Support @multipartBody for `bodyParam` of `SdkHttpOperation`
- Only property of multipart body shall be added `multipartOptions` and the property of base model shall have no `multipartOptions`
> [Multipart][TCGC] Support @multipartBody for `bodyParam` of `SdkHttpOperation`

- .chronus/changes/add-access-to-namespace-2024-7-6-15-15-43.md
- docs/libraries/typespec-client-generator-core/reference/decorators.md
- packages/typespec-client-generator-core/README.md
- packages/typespec-client-generator-core/generated-defs/Azure.ClientGenerator.Core.ts
- packages/typespec-client-generator-core/lib/decorators.tsp
- packages/typespec-client-generator-core/src/decorators.ts
- packages/typespec-client-generator-core/test/decorators.test.ts
> Add namespace as target for @access decorator

- .chronus/changes/release-august-2024-2024-7-12-14-21-18.md
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/types/built-in-types.test.ts
Problem on TCGC 0.45.1 here https://github.com/Azure/cadl-ranch/pull/656#discussion_r1713119741
link https://github.com/Azure/typespec-azure/issues/1264
link https://github.com/Azure/typespec-azure/issues/1179
> tcgc, bug fix on encode string

- .chronus/changes/tcgc-fix-get-library-name-2024-7-15-13-4-27.md
- packages/typespec-client-generator-core/src/public-utils.ts
- packages/typespec-client-generator-core/test/types/model-types.test.ts
After https://github.com/microsoft/typespec/pull/4144, anonymous model type may also have templateMapper arguments. For this scenario, `getLibraryName` shall not try to generate name from arguments, otherwise may generate model with duplicated name.
> [Tcgc] Fix getLibraryName for anonymous model which is derived from template

- .chronus/changes/fix_usage-2024-7-15-13-21-20.md
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/decorators.test.ts
- packages/typespec-client-generator-core/test/public-utils.test.ts
- packages/typespec-client-generator-core/test/types/body-model-property-types.test.ts
- packages/typespec-client-generator-core/test/types/built-in-types.test.ts
- packages/typespec-client-generator-core/test/types/constant-types.test.ts
- packages/typespec-client-generator-core/test/types/date-time-types.test.ts
- packages/typespec-client-generator-core/test/types/duration-type.test.ts
- packages/typespec-client-generator-core/test/types/enum-types.test.ts
- packages/typespec-client-generator-core/test/types/model-types.test.ts
- packages/typespec-client-generator-core/test/types/multipart-types.test.ts
- packages/typespec-client-generator-core/test/types/tuple-types.test.ts
- packages/typespec-client-generator-core/test/types/union-types.test.ts
this should be a bug that missing in https://github.com/Azure/typespec-azure/pull/925.
since we changed access default to public, we no longer need to add access override along with usage override when we want to expose an orphan model
> [tcgc] no need to add access override along with usage override for orphan model

- .chronus/changes/multipart-fix-2024-7-19-14-19-40.md
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/types/multipart-types.test.ts
Only after loop all clients, it is time to handle orphan models/enums/unions.
> [TCGC] Fix multipart for client customization

- .chronus/changes/tcgc-sync-body-param-encode-2024-7-22-16-51-43.md
- packages/typespec-client-generator-core/src/package.ts
- packages/typespec-client-generator-core/test/types/bytes-types.test.ts
- after fetching the sdk method body parameter, reset its encode according to the underlying http request content-type
- add unit test
fix #1084
> fix(tcgc): set sdk method body parameter encode with http content type

- .chronus/changes/fix-dup-services-2024-7-27-16-13-52.md
- packages/samples/test/output/core/rest-metadata-emitter/@azure-tools/typespec-autorest/AnotherService/openapi.json
- packages/typespec-autorest/src/openapi.ts
- packages/typespec-autorest/test/services.test.ts
Fixes #1373
Note: Had to regenerate one of the sample specs that was testing emitting multiple services - it turned out to be broken prior to this change as well.
> Fixes typespec-autorest openapi output when multiple services are defined

- .chronus/changes/tcgc-override-apiVersion-2024-7-27-13-4-58.md
- packages/typespec-client-generator-core/src/decorators.ts
- packages/typespec-client-generator-core/test/decorators.test.ts
With `@override`, we require a 1:1 mapping between the actual parameters and the parameters passed in your method signature override. However, this causes issues with `core`-introduced parameters because of template-related issues. On a higher level though, I think it's fair to not require `core` params in the method signature, since we already hide these parameters in the method signature, and these parameters will still be eventually set to the service
cc @trangevi
> [tcgc] don't require core-introduced params with `@override`

- .chronus/changes/autorest-clientname-2024-7-30-11-5-20.md
- packages/typespec-autorest/src/openapi.ts
- packages/typespec-autorest/test/models.test.ts
- packages/typespec-autorest/test/parameters.test.ts
- packages/typespec-autorest/test/union-schema.test.ts
fix [#442](https://github.com/Azure/typespec-azure/issues/442)
`@clientName` is respected for:
- definition names
- enum values names
- parameters names(for body it replace the `name` for other it adds `x-ms-client-name`)
Doing this now as this will help getting rid of some use of `@extension` 
This makes this doc accurate now https://azure.github.io/typespec-azure/docs/next/migrate-swagger/faq/breakingchange#createorupdate-put-apis as well
> Autorest respect clientName in more places

- .chronus/changes/fix-add-legacy-json-name-2024-8-3-8-9-1.md
- packages/typespec-autorest/src/openapi.ts
- packages/typespec-autorest/test/parameters.test.ts
Having `@clientName` just always override the name instead of setting x-ms-client-name result in many spec having their param change completely which is then detected as breaking change even though it isn't really. 
As there is a decent amount of failures for this (~130) i think its easier if for now we can just add an escape hatch
> Add back legacy way to specify body param name

- .chronus/changes/fix-tcgc-client-init-2024-8-5-13-31-51.md
- packages/typespec-client-generator-core/package.json
- packages/typespec-client-generator-core/src/package.ts
- packages/typespec-client-generator-core/test/package.test.ts
- packages/typespec-client-generator-core/test/test-host.ts
- pnpm-lock.yaml
> [TCGC] Fix client initialization for `subscriptionId`

- .chronus/changes/allow-reserved-2024-8-11-16-40-29.md
- packages/typespec-azure-resource-manager/lib/common-types/types.tsp
- packages/typespec-azure-resource-manager/lib/parameters.tsp
This is blocking a new RP [kubernetesruntime](https://github.com/Azure/azure-rest-api-specs/blob/f5321f9b29083f9ea4c028e7484504875e04a758/specification/kubernetesruntime/KubernetesRuntime.Management/storageclass.tsp#L273) generating SDK.
> Replace `x-ms-skip-url-encoding` with `allowReserved`

- eng/feeds/arm-canonical/tspconfig.yaml
- eng/feeds/arm/tspconfig.yaml
- eng/feeds/arm/tspconfig_stand_alone.yaml
- eng/feeds/data-plane/tspconfig.yaml
- eng/feeds/data-plane/tspconfig_stand_alone.yaml
Remove `examples-directory` option from the templates as the default value is already that now.
> Remove examples-directory from feeds 

- .chronus/changes/update-references-for-recent-changes-2024-8-14-12-27-46.md
- docs/howtos/Client Generation/07tcgcTypes.mdx
- packages/typespec-client-generator-core/src/interfaces.ts
Update references after merged #1463
> [TCGC] update references for #1463

- .chronus/changes/optional-encode-2024-8-14-9-51-14.md
- docs/howtos/Client Generation/07tcgcTypes.mdx
- packages/typespec-client-generator-core/src/interfaces.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/types/built-in-types.test.ts
Fixes https://github.com/Azure/typespec-azure/issues/875
> [TCGC] Change `encode` to optional and no longer use `kind` as its fallback value if there is no encode

- packages/website/package.json
- pnpm-lock.yaml
Docusaurus https://github.com/facebook/docusaurus/issues/9303 doesn't like some css nesting that monaco editor started using in 0.47.0
For now same as typespec repo we pin to old version of the editor.
Seems like however we might be able to build with `USE_SIMPLE_CSS_MINIFIER=true`
> Fix monaco editor freeze

- .chronus/changes/almend-DefaultValueScalarObject-2024-8-16-12-2-59.md
- packages/typespec-autorest/src/lib.ts
- packages/typespec-autorest/src/openapi.ts
- packages/typespec-autorest/test/models.test.ts
Issue: https://github.com/microsoft/typespec/issues/4238
> Default values supporting scalar and object

- .chronus/changes/onClientSetting-2024-8-17-17-22-46.md
- packages/typespec-client-generator-core/src/internal-utils.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/decorators.test.ts
> [tcgc] fix `onClient` setting for parameters applied to interface @clientInitialization

- .chronus/changes/handle-orphan-model-in-nested-ns-2024-8-18-15-54-46.md
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/decorators/usage.test.ts
fix: https://github.com/Azure/typespec-azure/issues/1531
> [tcgc] handle orphan types in nested namespaces

- .chronus/changes/change-response-to-be-array-2024-8-14-11-27-13.md
- docs/howtos/Client Generation/07tcgcTypes.mdx
- packages/typespec-client-generator-core/src/example.ts
- packages/typespec-client-generator-core/src/http.ts
- packages/typespec-client-generator-core/src/interfaces.ts
- packages/typespec-client-generator-core/src/internal-utils.ts
- packages/typespec-client-generator-core/test/examples/example-types.test.ts
- packages/typespec-client-generator-core/test/examples/http-operation-examples.test.ts
- packages/typespec-client-generator-core/test/package.test.ts
- packages/typespec-client-generator-core/test/packages/parameters.test.ts
- packages/typespec-client-generator-core/test/packages/spread.test.ts
Fixes https://github.com/Azure/typespec-azure/issues/1453
This is a breaking change in TCGC, but there are some reasons of making this change:
1. The `HttpOperation.responses` from typespec core library also defines as an array. 
2. The type `Map` is not persistable in typescript, which causes issues in some emitter implementation such as dotnet, because it needs to serialize everything in TCGC output and sends it to the generator written in other language (details [here](https://github.com/Azure/autorest.csharp/issues/5028))
3. In most cases, we have no more than 4 responses corresponding different status codes. In the majority of cases, we have 2 or 1. In such a small collections, maps do not have distinguishable performance improvement comparing with arrays with `find`, and arrays have …
> [TCGC] Change the `responses` and `exceptions` to be arrays

- .chronus/changes/fix-multipart-diagnostics-2024-8-13-13-31-25.md
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/types/multipart-types.test.ts
fix https://github.com/Azure/typespec-azure/issues/1510
> [TCGC] Fix judge logic how to distinguish model is referred both in common content-type and multipart content-type

- .chronus/changes/refine-responses-exceptions-2024-8-23-3-2-46.md
- packages/typespec-client-generator-core/src/http.ts
- packages/typespec-client-generator-core/src/interfaces.ts
Fixes https://github.com/Azure/typespec-azure/issues/1590
In `0.46.1` we changed the type of `responses` in `SdkHttpOperation` from `Map<number | HttpRange, SdkHttpResponse>` to `SdkHttpResponse[]`, `exceptions` in `SdkHttpOperation` from `Map<number | HttpRange | "*", SdkHttpResponse>` to `SdkHttpResponse[]`,
and added a `statusCodes` property to `SdkHttpResponse`. But the `statusCodes` is defined as `number | HttpRange | "*"`, which loses the information that the responses in `responses` property could never have a `*` as its statusCodes.
This PR adds a new type `SdkHttpErrorResponse` with the `statusCodes` of `number | HttpRange | "*"`, and changes the type of `statusCodes` in `SdkHttpResponse` to `number | HttpRange` to be precise.
> Refine the `statusCodes` of `responses` and `exceptions`

- .chronus/changes/fix_example_mapping-2024-8-24-14-45-21.md
- packages/typespec-client-generator-core/src/example.ts
- packages/typespec-client-generator-core/test/examples/load.test.ts
- packages/typespec-client-generator-core/test/examples/load/clientNameAnotherOriginal.json
- packages/typespec-client-generator-core/test/examples/load/clientNameOriginal.json
fix: https://github.com/Azure/typespec-azure/issues/1593
> [tcgc] change example mapping logic to allow operation id with/without renaming

- .chronus/changes/deprecate_description-2024-8-26-23-19-32.md
- packages/typespec-client-generator-core/src/example.ts
- packages/typespec-client-generator-core/src/interfaces.ts
Add back description and make it deprecated to prevent breaking in current version.
> [tcgc] deprecate description in `SdkExampleBase`

- .chronus/changes/update-core-854024a-2024-9-9-9-46-21.md
- packages/typespec-autorest/test/options.test.ts
- packages/typespec-client-generator-core/src/internal-utils.ts
- pnpm-lock.yaml
Created this PR instead of using dependabot due to new packages in `core` requiring the pnpm-lock file being updated.
Also updated TCGC to no longer grab projected source models since https://github.com/microsoft/typespec/pull/4445 updated  core to project the source models already.
> Update core submodule to 854024a

- .chronus/changes/fix_spread_body-2024-9-10-14-19-3.md
- packages/typespec-client-generator-core/src/http.ts
- packages/typespec-client-generator-core/src/internal-utils.ts
- packages/typespec-client-generator-core/src/public-utils.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/packages/spread.test.ts
because of this fix: https://github.com/microsoft/typespec/issues/4280, tcgc should not do projection again which will cause undefined issue when finding spread body model.
> [tcgc] remove projection for source model since typespec core has already fixed the issue

- packages/azure-http-specs/package.json
- packages/azure-http-specs/specs/azure/client-generator-core/access/mockapi.ts
- packages/azure-http-specs/specs/azure/client-generator-core/flatten-property/mockapi.ts
- packages/azure-http-specs/specs/azure/client-generator-core/usage/mockapi.ts
- packages/azure-http-specs/specs/azure/core/basic/mockapi.ts
- packages/azure-http-specs/specs/azure/core/lro/standard/mockapi.ts
- packages/azure-http-specs/specs/azure/core/model/mockapi.ts
- packages/azure-http-specs/specs/azure/core/page/mockapi.ts
- packages/azure-http-specs/specs/azure/core/scalar/mockapi.ts
- packages/azure-http-specs/specs/azure/core/traits/mockapi.ts
- packages/azure-http-specs/specs/azure/example/basic/mockapi.ts
- packages/azure-http-specs/specs/azure/resource-manager/models/common-types/managed-identity/mockapi.ts
- packages/azure-http-specs/specs/azure/resource-manager/models/resources/mockapi.ts
- packages/azure-http-specs/specs/client/naming/mockapi.ts
- packages/azure-http-specs/specs/client/structure/common/service.ts
- packages/azure-http-specs/specs/resiliency/srv-driven/mockapi.ts
This is the continuation of the PR https://github.com/microsoft/typespec/pull/4725. This PR handles the removal of handler property in majority of the Scenarios (Except ones related to LRO and that checks the absence of a parameter). All Scenarios are validated and tested. Please review and approve the PR. Thanks
> [@azure-tools/azure-http-specs] - Remove handler for majority of the Scenarios

- packages/azure-http-specs/spec-summary.md
- packages/azure-http-specs/specs/azure/client-generator-core/access/main.tsp
- packages/azure-http-specs/specs/azure/client-generator-core/usage/main.tsp
- packages/azure-http-specs/specs/azure/core/traits/mockapi.ts
This PR is the `typespec-azure` counterpart of the PR https://github.com/microsoft/typespec/pull/4799. These changes are required in the specs to handle the test success in `http-client-java`, `http-client-net` and `http-client-python` packages. The scenarios are also validated using the `test:e2e` script.
Please review and approve the PR. Thanks
> [@azure-tools/azure-http-specs] - Modify code to handle http-client-* packages tests

- .chronus/changes/fix_anony-2024-9-23-20-44-2.md
- packages/typespec-client-generator-core/src/public-utils.ts
- packages/typespec-client-generator-core/test/public-utils.test.ts
when comparing, we should use the model before `getEffectiveModelType`.
fix: https://github.com/Azure/typespec-azure/issues/1730
> [tcgc] fix wrong compare target for response body with anonymous model when finding anonymous model context

- .chronus/changes/types_order-2024-9-31-14-3-9.md
- packages/typespec-client-generator-core/src/types.ts
fix: https://github.com/Azure/typespec-azure/issues/1394
> [tcgc] use array instead of set to make the types ordered by typespec definition

- .chronus/changes/fix_route_param-2024-9-31-18-1-39.md
- packages/typespec-client-generator-core/src/http.ts
- packages/typespec-client-generator-core/test/package.test.ts
- packages/typespec-client-generator-core/test/packages/parameters.test.ts
fix: https://github.com/Azure/typespec-azure/issues/1709
fix: https://github.com/Azure/typespec-azure/issues/1728
> [tcgc] remove unused path parameter from method

- .github/policies/issues.triage.generated.yml
- .github/policies/prs.triage.generated.yml
- CONTRIBUTING.md
- eng/config/labels.ts
Label was added and is now making the CI fail for every PR as there is one issue assigned to it so we don't auto delete
> Add ide label for azure specific ide requests

- .chronus/changes/add_usage_helper-2024-10-11-17-1-36.md
- packages/typespec-client-generator-core/src/decorators.ts
- packages/typespec-client-generator-core/src/interfaces.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/decorators/access.test.ts
- packages/typespec-client-generator-core/test/decorators/usage.test.ts
- packages/typespec-client-generator-core/test/types/model-types.test.ts
resolve: https://github.com/Azure/typespec-azure/issues/1827
add `disableUsageAccessPropagationToBase` flag: this flag aims to support language that does not generate base model, it will skip the base model's propagation but will not skip the property or subtype of the base model.
> [tcgc] add `disableUsageAccessPropagationToBase` flag and separate exception usage from output usage

- website/src/content/docs/docs/howtos/Generate client libraries/02client.mdx
- website/src/content/docs/docs/howtos/Generate client libraries/03convenient.mdx
- website/src/content/docs/docs/howtos/Generate client libraries/04renaming.mdx
- website/src/content/docs/docs/howtos/Generate client libraries/06types.mdx
Update/complete doc on Java emitter's behavior upon TypeSpec Namespace and `@clientNamespace`.
> doc, howto, update java on namespace

- .chronus/changes/specs_clientNamespace-for-java-2024-10-22-10-38-54.md
- packages/azure-http-specs/specs/azure/example/basic/client.tsp
backport https://github.com/Azure/cadl-ranch/pull/771
After this, Java would start the migration to http-specs/azure-http-specs and no longer update cadl-ranch
> specs, clientNamespace for Java

- .chronus/changes/fix_path_param_filtering-2024-10-25-14-34-24.md
- packages/typespec-client-generator-core/src/http.ts
- packages/typespec-client-generator-core/test/packages/parameters.test.ts
fix: https://github.com/Azure/typespec-azure/issues/1905
> [tcgc] use the right path parameter name when filtering method parameter

- .chronus/changes/common_paging-2024-10-27-16-28-24.md
- package.json
- packages/typespec-client-generator-core/CHANGELOG.md
- packages/typespec-client-generator-core/src/decorators.ts
- packages/typespec-client-generator-core/src/interfaces.ts
- packages/typespec-client-generator-core/src/lib.ts
- packages/typespec-client-generator-core/src/package.ts
- packages/typespec-client-generator-core/src/public-utils.ts
- packages/typespec-client-generator-core/test/packages/paged-operation.test.ts
support typespec common paging.
currently, typspec does not support using pageable decorator in nested properties, related test is skipped.
> [tcgc] support typespec common paging

- .chronus/changes/fix_unbranded_page_issue-2024-10-29-17-58-58.md
- packages/typespec-client-generator-core/src/package.ts
- packages/typespec-client-generator-core/test/packages/paged-operation.test.ts
when a method has several responses and only one of them has pageable body. tcgc's method return type will be a wrapped nullable type which real type is that response with body. so, when trying to find property, we need to peel off the wrapped nullable.
> [tcgc] fix wrong `unexpected-pageable-operation-return-type` because of nullable type

- .chronus/changes/cookie_support-2024-10-6-16-23-46.md
- packages/typespec-client-generator-core/src/http.ts
- packages/typespec-client-generator-core/src/interfaces.ts
- packages/typespec-client-generator-core/test/packages/parameters.test.ts
resolve: https://github.com/Azure/typespec-azure/issues/1792
> [tcgc] add `SdkCookieParameter` type and support `@cookie` in TypeSpec http lib

- eng/pipelines/deploy-azure-spec-dashboard-storage-account.yml
This PR creates the pipeline for Deployment of the Azure Spec Dashboard. Please review and approve the PR. Thanks
> [@azure-tools/azure-spec-dashboard] Deployment script for Azure Spec Dashboard

- website/src/content/docs/docs/howtos/Generate client libraries/00howtogen.mdx
While we have issues to remove `flavor` for `azure-tools` emitters, matter of fact is that today it's needed, and people got confused following the tutorial today (for good reasons).
I'll do a PR once we change the default, it may be in several months given this is not a priority.
> Add flavor in Azure tutorial

- .chronus/changes/scope-decorator-2024-11-18-12-59-12.md
- packages/typespec-client-generator-core/README.md
- packages/typespec-client-generator-core/generated-defs/Azure.ClientGenerator.Core.ts
- packages/typespec-client-generator-core/lib/decorators.tsp
- packages/typespec-client-generator-core/src/decorators.ts
- packages/typespec-client-generator-core/src/internal-utils.ts
- packages/typespec-client-generator-core/src/package.ts
- packages/typespec-client-generator-core/src/tsp-index.ts
- packages/typespec-client-generator-core/test/decorators.test.ts
- website/src/content/docs/docs/libraries/typespec-client-generator-core/reference/decorators.md
- website/src/content/docs/docs/libraries/typespec-client-generator-core/reference/index.mdx
Resolves #964
The scope parameter of `@scope` decorator is not working as the normal decorator.
For a normal decorator, we need to get the decorator value from state map based on the scope and the current emitter name. If the value hit from the state map with current emitter name, it's a positive case, if not hit, it's a negative case.
```
@clientName("Renamed", csharp)
model A;
```
With the normal decorator scope handling, if the decorator is absent it is a negative case. For the case below, we don't need to handle `@clientname` decorator, it is a negative case.
```
model A;
```
But for `@scope` decorator, when it is absent, it means `AllScopes`, which is also a positive case. For below two cases, python emitter should include this operation, both of them are positive case.
```
op func: …
```
> Add `@scope` decorator

- .chronus/changes/tcgc-crxlangdefid-2025-0-3-16-45-47.md
- packages/typespec-client-generator-core/src/package.ts
- packages/typespec-client-generator-core/src/public-utils.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/packages/client.test.ts
- packages/typespec-client-generator-core/test/public-utils.test.ts
- packages/typespec-client-generator-core/test/public-utils/get-cross-language-definition-id.test.ts
- packages/typespec-client-generator-core/test/types/enum-types.test.ts
1. refine all generated type's cross language definition id
2. for parameters, use the operation name as the prefix of cross language definition id
3. for anonymous model, add namespace for first section of the cross language definition id
fix: https://github.com/Azure/typespec-azure/issues/2031
> [tcgc] refine cross language definition id logic

- .github/CODEOWNERS
Porting the cadl-ranch owners, so Codegen team can approve new tests autonomously
https://github.com/Azure/cadl-ranch/blob/30c3d78c3672c3dd2f81d6d91380e177f0566b44/.github/CODEOWNERS#L2C34-L2C112
> Add Codegen owners to spector specs

- .chronus/changes/fix_regression-2025-0-22-14-2-17.md
- .chronus/changes/fix_regression-2025-0-22-14-2-45.md
- packages/typespec-client-generator-core/src/example.ts
- packages/typespec-client-generator-core/src/interfaces.ts
- packages/typespec-client-generator-core/test/examples/example-types.test.ts
- packages/typespec-client-generator-core/test/examples/example-types/getModelWithExtraParamter.json
- packages/typespec-client-generator-core/test/types/serialization-options.test.ts
1. Deprecate `serializedName` property of `SdkEndpointParameter`. Use `type.templateArguments[x].serializedName` or `type.variantTypes[x].templateArguments[x].serializedName` instead.
2. Fix regression of example mapping for model with parameters.
> [tcgc] fix regression of 0.50.1

- .chronus/changes/fix-duplicate-warning-2025-0-15-11-39-29.md
- packages/typespec-azure-resource-manager/src/rules/no-response-body.ts
- packages/typespec-azure-resource-manager/test/rules/no-response-body.test.ts
issue: https://github.com/Azure/typespec-azure/issues/1785
>  Exclude template instances from the `no-response-body` rule.

- website/src/content/docs/docs/migrate-swagger/01-get-started.md
After this PR https://github.com/Azure/azure-sdk-tools/pull/9602, `@autorest/openapi-to-typespec` no longer updated with tsp-client. Customers need to update themselves every time when `@autorest/openapi-to-typespec` release. This document update is to guide customers how to updadte.
> Update converter document

- .chronus/changes/fix-typo-in-privateLinkResourcenName-2025-1-7-11-23-20.md
- packages/typespec-azure-resource-manager/lib/common-types/private-links.tsp
Bug reported in: https://github.com/Azure/typespec-azure/issues/2183
> Fix Typo mistake in @key("privateLinkResourcenName"). Change from privateLinkResourcenName to privateLinkResourceName 

- .chronus/changes/azure-http-specs_config-java-namespace-2025-1-8-11-59-45.md
- packages/azure-http-specs/specs/azure/client-generator-core/access/main.tsp
- packages/azure-http-specs/specs/azure/client-generator-core/api-version/header/client.tsp
- packages/azure-http-specs/specs/azure/client-generator-core/api-version/path/client.tsp
- packages/azure-http-specs/specs/azure/client-generator-core/api-version/query/client.tsp
- packages/azure-http-specs/specs/azure/client-generator-core/flatten-property/main.tsp
- packages/azure-http-specs/specs/azure/client-generator-core/usage/main.tsp
- packages/azure-http-specs/specs/azure/core/basic/client.tsp
- packages/azure-http-specs/specs/azure/core/lro/rpc/main.tsp
- packages/azure-http-specs/specs/azure/core/lro/standard/main.tsp
- packages/azure-http-specs/specs/azure/core/model/main.tsp
- packages/azure-http-specs/specs/azure/core/page/main.tsp
- packages/azure-http-specs/specs/azure/core/scalar/main.tsp
- packages/azure-http-specs/specs/azure/core/traits/main.tsp
context: Java does not want to see the default `_specs_` in its namespace https://github.com/Azure/autorest.java/tree/main/typespec-tests/src/main/java/_specs_
> azure-http-specs, config java namespace, avoid _Specs_ appear in SDK namespace

- .chronus/changes/rename_namespace-2025-1-14-17-4-43.md
- packages/typespec-client-generator-core/src/interfaces.ts
- packages/typespec-client-generator-core/src/package.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/decorators/client-namespace.test.ts
- packages/typespec-client-generator-core/test/packages/namespaces.test.ts
Deprecate `clientNamespace` property in `SdkClientType`, `SdkNullableType`, `SdkEnumType`, `SdkUnionType` and `SdkModelType`. Use `namespace` instead.
fix: https://github.com/Azure/typespec-azure/issues/2123
> [tcgc] rename `clientNamespace` into `namespace` directly

- .chronus/changes/fix_result_path-2025-1-19-14-38-26.md
- packages/typespec-client-generator-core/src/package.ts
- packages/typespec-client-generator-core/test/packages/paged-operation.test.ts
for any spread cases, we need to use root source property to do the comparison.
> [tcgc] fix missing result segments of anonymous paged response with header

- .chronus/changes/fix_property-2025-1-24-11-55-32.md
- .chronus/changes/fix_property-2025-1-24-11-56-21.md
- packages/typespec-client-generator-core/src/context.ts
- packages/typespec-client-generator-core/src/http.ts
- packages/typespec-client-generator-core/src/interfaces.ts
- packages/typespec-client-generator-core/src/package.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/package.test.ts
- packages/typespec-client-generator-core/test/packages/parameters.test.ts
- packages/typespec-client-generator-core/test/types/enum-types.test.ts
- packages/typespec-client-generator-core/test/types/model-types.test.ts
- packages/typespec-client-generator-core/test/types/union-types.test.ts
fix: https://github.com/Azure/typespec-azure/issues/2251
`isGeneratedName` always set to true only when it is the inner type of nullable union.
Remove parameter cache to retain HTTP metadata info for model property.
> [tcgc] fix regression of 0.51.2

- eng/pipelines/jobs/e2e-job.yml
- packages/e2e-tests/azure-http-specs/package.json
- packages/e2e-tests/cadl-ranch-specs/package.json
- packages/e2e-tests/e2e-tests.mjs
cadl-ranch has been archived. This is also blocking core updates because we aren't updating the old cadl-ranch specs anymore:
https://github.com/Azure/typespec-azure/pull/2270
> switch e2e tests from cadl-ranch to azure-http-specs

- .chronus/changes/witemple-msft-autorest-invisible-fix-2025-2-4-16-21-51.md
- packages/typespec-autorest/src/openapi.ts
- packages/typespec-autorest/test/arm/resources.test.ts
This PR fixes a bug with the handling of `@invisible(Lifecycle)` in typespec-autorest. Currently, it considers a property shareable if it either has default visibility (all modifiers), or if it does not contain any modifiers that cannot be expressed through x-ms-mutability. This was almost correct, except for the case where the property is _completely invisible_, in which case the property cannot be shared. This behavior was unique to typespec-autorest due to its logic around handling x-ms-mutability and the openapi3 emitter was not affected because it only attempts to share read-only properties.
In practice, `@invisible(Lifecycle)` is extremely rarely used because it means that the property would not be present in any operation payloads.
This PR adds a test against regressions ensuring …
> [typespec-autorest] Fix logic around `canShare` and `@invisible`

- .chronus/changes/rm-is-content-type-header-2025-2-7-10-57-21.md
- packages/typespec-autorest/src/openapi.ts
- pnpm-lock.yaml
Similar to OpenAPI3 changes in https://github.com/microsoft/typespec/pull/6311
> typespec-autorest - remove usage of deprecated isContentTypeHeader

- .chronus/changes/azure-http-specs_validate-orphan-model-serializable-2025-2-6-14-48-18.md
- packages/azure-http-specs/spec-summary.md
- packages/azure-http-specs/specs/azure/client-generator-core/usage/main.tsp
- packages/azure-http-specs/specs/azure/client-generator-core/usage/mockapi.ts
- packages/azure-http-specs/specs/azure/core/traits/main.tsp
As discussed, we want to verify that an orphan model is by default serializable as JSON.
Since there were an existing test on orphan model, I just enhanced it and added an operation to verify the serialization.
> azure-http-specs, validate orphan model serializable

- .chronus/changes/fix-unsupported-param-target-2025-1-24-23-11-54.md
- packages/typespec-autorest/src/openapi.ts
This allows suppressing the error message
unblock https://github.com/microsoft/typespec/issues/6110
> Fix: Target param property when error on invalid type

- .chronus/changes/tcgc-fixApiVersionNestedClientDefaultValue-2025-2-10-15-42-42.md
- .chronus/changes/tcgc-fixApiVersionNestedClientDefaultValue-2025-2-10-15-44-40.md
- packages/typespec-client-generator-core/src/internal-utils.ts
- packages/typespec-client-generator-core/src/package.ts
- packages/typespec-client-generator-core/src/public-utils.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/decorators/client.test.ts
- packages/typespec-client-generator-core/test/internal-utils.test.ts
fixes #2313
The issue was that previously we only went down one-level of subclients: we didn't recurse to go through all subclients when setting `.clientDefaultValue` for api versions and others.
This PR adds deeper recursion, updates other places in code where we run into this issue, and removes an unused public-utils function to avoid confusion
> [tcgc] fix api version nested client default value

- .chronus/changes/export_list_service-2025-2-13-10-47-21.md
- packages/typespec-client-generator-core/src/decorators.ts
- packages/typespec-client-generator-core/src/internal-utils.ts
- packages/typespec-client-generator-core/src/package.ts
- packages/typespec-client-generator-core/src/public-utils.ts
- packages/typespec-client-generator-core/test/utils.ts
the exported `listAllServiceNamespaces` function will help to list all namespaces with `@service` decorator with latest api version for versioning service by default. mainly for rlc usage.
> [tcgc[ export `listAllServiceNamespaces`

- .chronus/changes/uptake-cleanup-http-2025-2-13-16-39-43.md
- packages/typespec-azure-core/test/test-host.ts
- packages/typespec-azure-resource-manager/lib/models.tsp
- packages/typespec-azure-resource-manager/src/namespace.ts
- packages/typespec-azure-resource-manager/test/lro-metadata.test.ts
Uptake change required by this pr https://github.com/microsoft/typespec/pull/6433
There is a few spec that use the includePayload decorator but they are all marked as a pattern you shoul;dn't do already using internal apis so we'll just add `Private.` in front and we'll have to figure out how to solve this so we can completely remove the decorator
> Uptake cleanup of http library

- .chronus/changes/witemple-msft-media-type-hint-2025-2-14-16-25-14.md
- .gitmodules
- packages/samples/test/output/core/grpc-library-example/@azure-tools/typespec-autorest/openapi.json
- packages/samples/test/output/core/init/@azure-tools/typespec-autorest/openapi.json
- packages/samples/test/output/core/nested/@azure-tools/typespec-autorest/openapi.json
- packages/samples/test/output/core/optional/@azure-tools/typespec-autorest/openapi.json
- packages/samples/test/output/core/simple/@azure-tools/typespec-autorest/openapi.json
- packages/samples/test/output/core/testserver/body-boolean/@azure-tools/typespec-autorest/openapi.json
- packages/samples/test/output/core/testserver/body-string/@azure-tools/typespec-autorest/openapi.json
- packages/samples/test/output/core/testserver/body-time/@azure-tools/typespec-autorest/openapi.json
- packages/samples/test/output/core/testserver/media-types/@azure-tools/typespec-autorest/openapi.json
- packages/samples/test/output/core/testserver/multiple-inheritance/@azure-tools/typespec-autorest/openapi.json
- packages/typespec-autorest-canonical/test/return-types.test.ts
- packages/typespec-autorest/test/metadata.test.ts
- packages/typespec-autorest/test/openapi-output.test.ts
- packages/typespec-autorest/test/parameters.test.ts
- packages/typespec-autorest/test/return-types.test.ts
- packages/typespec-autorest/test/services.test.ts
- packages/typespec-client-generator-core/src/http.ts
- packages/typespec-client-generator-core/src/media-types.ts
- packages/typespec-client-generator-core/test/methods/parameters.test.ts
This is the Azure companion of https://github.com/microsoft/typespec/pull/6357
This PR updates the recorded sample output to account for changes to the default content types of scalars.
> Validate and update sample output for media type hint change

- .chronus/changes/export_schema-2025-2-17-11-42-28.md
- packages/typespec-client-generator-core/src/lib.ts
Export `SdkEmitterOptionsSchema` for downstream emitter to add same options.
> [tcgc] export `SdkEmitterOptionsSchema`

- .chronus/changes/tcgc-fix_visibility-2025-2-18-14-24-28.md
- packages/typespec-client-generator-core/src/http.ts
- packages/typespec-client-generator-core/src/public-utils.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/methods/responses.test.ts
with previous logic, http library will return a created anonymous model without `Create` visibility, and tcgc could not find the original model, but use this anonymous model as the response type (`GetResponse`). see [playground](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=QHNlcnZpY2UNCm5hbWVzcGFjZSBUZXN0Q2xpZW50IHsNCiAgbW9kZWzFFsYQICBAdmlzaWJpbGl0eShMaWZlY3ljbGUuQ3JlYXRlKcYjY8UNOiBzdHJpbmc7DQrGF3JlYWTLFSAgfcYab3AgZ2V0KCk6xWg7DQp9DQo%3D&e=%40azure-tools%2Ftypespec-client-generator-core&options=%7B%7D), line 59.
with current logic, tcgc could find the original model and will use that model as the response type (`Test`). see [playground](https://cadlplayground.z22.web.core.windows.net/typespec-azure/prs/2402/?c=QHNlcnZpY2UNCm5hbWVzcGFjZSBUZXN0Q2xpZW50IHsNCiAgbW9kZWzFFsYQICBA …
> [tcgc] ignore visibility when finding response type if it is anonymous model

- .chronus/changes/remove_duplicate-2025-2-24-14-19-54.md
- packages/typespec-client-generator-core/src/license.ts
> [tcgc] remove duplicate line for build-in license info

- .chronus/changes/fix-multipart-issues-2025-2-28-2-35-5.md
- packages/typespec-autorest/src/openapi.ts
- packages/typespec-autorest/test/multipart.test.ts
fix  #2462 `x-ms-client-name` not applied when part has a different name from property
fix  #2463 Description on targeted schema won over the property description
> Fix multipart issues

- .chronus/changes/tcgc-emitterOptionsSplit-2025-2-25-17-26-43.md
- packages/typespec-client-generator-core/README.md
- packages/typespec-client-generator-core/src/context.ts
- packages/typespec-client-generator-core/src/internal-utils.ts
- packages/typespec-client-generator-core/src/lib.ts
- packages/typespec-client-generator-core/test/namespaces.test.ts
- packages/typespec-client-generator-core/test/test-host.ts
- website/src/content/docs/docs/libraries/typespec-client-generator-core/reference/emitter.md
BREAKING: emitter options will now be individually exposed and split into `BrandedSdkEmitterOptions` and `UnbrandedSdkEmitterOptions`. This change allows emitters to choose which flags to support, BUT it means that you will have to explicitly choose the flags to support. Example code snippet in an emitter:
```ts
import { BrandedSdkEmitterOptions, UnbrandedSdkEmitterOptions } from "@azure-tools/typespec-client-generator-core"
const UnbrandedPythonEmitterOptionsSchema: JSONSchemaType<UnbrandedPythonEmitterOptions> = {
type: "object",
additionalProperties: true,
properties: {
"python-specific-flag": {...},
...UnbrandedSdkEmitterOptions["api-version"],
...UnbrandedSdkEmitterOptions["license"],
}
}
const BrandedPythonEmitterOptionsSchema: JSONSchemaType<BrandedPythonEmitterOptions> = {
type: …
```
> [tcgc] emitter options split

- .chronus/changes/fix_target-2025-2-31-11-39-58.md
- .chronus/changes/fix_target-2025-2-31-20-5-48.md
- packages/typespec-client-generator-core/src/http.ts
- packages/typespec-client-generator-core/src/lib.ts
- packages/typespec-client-generator-core/src/package.ts
- packages/typespec-client-generator-core/test/clients/params.test.ts
1. Change diagnostic target for `no-corresponding-method-param` error.
2. Change default endpoint's type to `url` and `allowReserved` to `true`.
fix: https://github.com/Azure/typespec-azure/issues/2468
> [tcgc] fix tcgc issues

- eng/feeds/__snapshots__/azure-core/tspconfig.yaml
- eng/feeds/__snapshots__/azure-core_stand_alone/tspconfig.yaml
- eng/feeds/data-plane/tspconfig.yaml
- eng/feeds/data-plane/tspconfig_stand_alone.yaml
Seems like all our init templates also had this invalid property set
> Fix invalid tsconfig from feed

- website/src/content/docs/docs/howtos/Generate client libraries/11etag.mdx
The typespec is already complete for sample and there is only missing for Go/js/C# examples.
@tadelesh / @MaryGao / @ArcturusZhang, please help add example code for your language.
> [doc][etag] Update doc

- .chronus/changes/azure-http-specs_improve-package-name-for-java-2025-3-10-21-19-5.md
- packages/azure-http-specs/specs/azure/client-generator-core/client-initialization/client.tsp
minor update to `client-initialization`, for package/namespace for Java (and avoid model to be generated in `service` package).
> azure-http-specs, override package name for java in test case

- .chronus/changes/tcgc-optional_path-2025-3-10-16-10-10.md
- packages/typespec-client-generator-core/src/http.ts
- packages/typespec-client-generator-core/src/interfaces.ts
- packages/typespec-client-generator-core/test/http/body.test.ts
- packages/typespec-client-generator-core/test/http/path.test.ts
fix: https://github.com/Azure/typespec-azure/issues/2495
for normal case, path and body parameter's optionality will follow typespec definition.
for spread body, only when all the properties are optional, the body is optional.
> [tcgc] fix optionality for path and body

- .chronus/changes/tcgc-example_fix-2025-3-11-15-19-7.md
- packages/typespec-client-generator-core/src/example.ts
- packages/typespec-client-generator-core/test/examples/example-types/getUnexpectedNull.json
- packages/typespec-client-generator-core/test/examples/types.test.ts
fix: https://github.com/Azure/typespec-azure/issues/2525
> [tcgc] always ignore `null` example value for non-nullable type

- .chronus/changes/specs-updatePythonClientNamespace-2025-3-14-14-48-44.md
- packages/azure-http-specs/specs/azure/client-generator-core/access/main.tsp
- packages/azure-http-specs/specs/azure/client-generator-core/api-version/header/client.tsp
- packages/azure-http-specs/specs/azure/client-generator-core/api-version/path/client.tsp
- packages/azure-http-specs/specs/azure/client-generator-core/api-version/query/client.tsp
- packages/azure-http-specs/specs/azure/client-generator-core/client-initialization/client.tsp
- packages/azure-http-specs/specs/azure/client-generator-core/flatten-property/main.tsp
- packages/azure-http-specs/specs/azure/client-generator-core/usage/main.tsp
- packages/azure-http-specs/specs/azure/core/basic/client.tsp
- packages/azure-http-specs/specs/azure/core/lro/rpc/main.tsp
- packages/azure-http-specs/specs/azure/core/lro/standard/main.tsp
- packages/azure-http-specs/specs/azure/core/model/main.tsp
- packages/azure-http-specs/specs/azure/core/page/main.tsp
- packages/azure-http-specs/specs/azure/core/scalar/main.tsp
- packages/azure-http-specs/specs/azure/core/traits/main.tsp
- packages/azure-http-specs/specs/azure/encode/duration/main.tsp
- packages/azure-http-specs/specs/azure/example/basic/client.tsp
- packages/azure-http-specs/specs/azure/payload/pageable/main.tsp
cc @msyyc @tadelesh . We can piggyback onto what java has done, this way we don't have to set the `namespace` for all of our azure generations. This will have a big change in the autorest.python repo, since I think we can also get rid of the `specs.` prefix from the namespaces
> [specs] update python client namespace

- .chronus/changes/fix_body-2025-3-21-11-48-17.md
- packages/typespec-client-generator-core/src/http.ts
- packages/typespec-client-generator-core/test/http/body.test.ts
rollback logic in: https://github.com/Azure/typespec-azure/pull/2556.
refer the discussion: https://github.com/microsoft/typespec/issues/1907
> [tcgc] spread body param is always required

- .chronus/changes/azure-http-specs_client-initialization-child-2025-3-16-17-25-6.md
- packages/azure-http-specs/spec-summary.md
- packages/azure-http-specs/specs/azure/client-generator-core/client-initialization/client.tsp
- packages/azure-http-specs/specs/azure/client-generator-core/client-initialization/main.tsp
- packages/azure-http-specs/specs/azure/client-generator-core/client-initialization/mockapi.ts
tested locally
```
var result = new ParentClientBuilder().buildClient()
.getChildClient("sample-blob")
.getStandalone();
new ChildClientBuilder().blobName("sample-blob").buildClient()
.deleteStandalone();
```
> azure-http-specs, client initialization with child client

- .chronus/changes/modify-ref-nullable-openapi-2025-3-23-9-58-51.md
- packages/samples/common-types/openapi/v3/managedidentity.json
- packages/samples/common-types/openapi/v4/managedidentity.json
- packages/samples/common-types/openapi/v5/managedidentity.json
- packages/samples/common-types/openapi/v6/managedidentity.json
- packages/samples/test/output/azure/resource-manager/arm-library/@azure-tools/typespec-autorest/2021-09-21-preview/openapi.json
- packages/samples/test/output/core/nullable/@azure-tools/typespec-autorest/openapi.json
- packages/typespec-autorest-canonical/test/union-schema.test.ts
- packages/typespec-autorest/src/openapi.ts
- packages/typespec-autorest/test/models.test.ts
- packages/typespec-autorest/test/openapi-output.test.ts
- packages/typespec-autorest/test/union-schema.test.ts
issue: https://github.com/Azure/typespec-azure/issues/1163#
> Modify how `x-nullable` is resolved next to `$ref` 

- .chronus/changes/azure-http-specs_fix-dyn-2025-3-30-18-28-19.md
- packages/azure-http-specs/specs/azure/resource-manager/operation-templates/mockapi.ts
@timotheeguerin
I've got 500 on this API, in nightly build (against unreleased azure-http-specs lib -- released one is good)
https://dev.azure.com/azure-sdk/public/_build/results?buildId=4814852&view=logs&j=ca395085-040a-526b-2ce8-bdc85f692774&t=1fb2445c-3c92-5f9b-bcad-710222d02bc3&l=274
So far, this appears to be the only place `dyn/dynItem` is used in handler. My guess is that this be a mistake.
Let me know if this is the not the correct fix.
> azure-http-specs, fix dyn in handler

- .chronus/changes/tcgc-cache_array_map-2025-4-6-18-37-49.md
- packages/typespec-client-generator-core/src/context.ts
- packages/typespec-client-generator-core/src/interfaces.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/types/array.test.ts
- packages/typespec-client-generator-core/test/types/dictionary.test.ts
fix: https://github.com/Azure/typespec-azure/issues/2595
> [tcgc] convert to same type for array or dictionary of same type

- .chronus/changes/opt-body-2025-4-12-19-18-0.md
- packages/azure-http-specs/spec-summary.md
- packages/samples/specs/resource-manager/legacy/optional-body/main.tsp
- packages/samples/test/output/azure/resource-manager/legacy/optional-body/@azure-tools/typespec-autorest/2025-01-01-preview/openapi.json
- packages/typespec-autorest/test/arm/resources.test.ts
- packages/typespec-azure-resource-manager/lib/Legacy/operations.tsp
- packages/typespec-azure-resource-manager/lib/foundations/arm.foundations.tsp
- packages/typespec-azure-resource-manager/lib/operations.tsp
- packages/typespec-azure-resource-manager/lib/parameters.tsp
- pnpm-lock.yaml
- website/src/content/docs/docs/libraries/azure-resource-manager/reference/data-types.md
- website/src/content/docs/docs/libraries/azure-resource-manager/reference/index.mdx
- website/src/content/docs/docs/libraries/azure-resource-manager/reference/interfaces.md
> Make request bodies optional

- .chronus/changes/azure_http_specs-large_header-2025-4-14-8-45-41.md
- packages/azure-http-specs/specs/azure/resource-manager/large-header/main.tsp
- packages/azure-http-specs/specs/azure/resource-manager/large-header/mockapi.ts
POST/DELETE LRO now requires that both `Location` and `AAO` headers are returned in response.
For each header value, [`Authorization`](https://eng.ms/docs/products/arm/api_contracts/asyncoperationsigningandvalidation) info will be appended at the end, making the URL much longer.
Thus, [doc](https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/async-operations#url-to-monitor-status) requires that REST client should accept **minimum** header size of 4KB.
Added a POST LRO which will return both `Location` and `AAO` headers with 6KB+ size each, 12KB+ size in total.
Ensure your HttpClient accepts both
1. 7KB single header size
2. 13KB total header size
> [azure-http-specs] add test for mgmt-plane large LRO header

- website/src/content/current-sidebar.ts
- website/src/content/docs/docs/emitters/clients/typespec-java/reference/emitter.md
- website/src/content/docs/docs/emitters/clients/typespec-java/reference/index.mdx
Add emitter doc for typespec-java
Currently it is generated from https://github.com/Azure/autorest.java/pull/3116
Typically, the change on emitter options is infrequent. And manual sync may not be too bad (till we find a better solution).
> doc, add emitter doc of typespec-java

- .chronus/changes/tcgc_fix-doc-2025-4-20-11-54-42.md
- packages/typespec-client-generator-core/README.md
- packages/typespec-client-generator-core/src/lib.ts
- website/src/content/docs/docs/libraries/typespec-client-generator-core/reference/emitter.md
the "description" on `generate-convenience-methods` was wrong.
> tcgc, Fix documentation on generate-convenience-methods option

- .chronus/changes/legacyOperationUpdate-2025-4-19-18-33-20.md
- packages/typespec-autorest/test/arm/resources.test.ts
- packages/typespec-azure-resource-manager/lib/Legacy/operations.tsp
- website/src/content/docs/docs/libraries/azure-resource-manager/reference/interfaces.md
I want to align the name to our previous design. Justifications:
1. Converter already aligns with these names. It costs to fix the logic in converter.
2. Current name is a breaking to all the ongoing migration PR. We need to rename a lot, including the operations and all the augmented decorators applied on the body name.
3. Current name is a breaking to haven't-merged Compute.
> Change the body name of legacy operations

- .chronus/changes/fix-http-part-file-2025-4-29-17-14-9.md
- packages/typespec-autorest/src/openapi.ts
- packages/typespec-autorest/test/multipart.test.ts
fix [#2661](https://github.com/Azure/typespec-azure/issues/2661)
> Fix HttpPart<File> correctly render as `type:file`

- eng/pipelines/jobs/e2e-job.yml
Resolves #2635 
E2E tests are already disabled for `publish/` branches. This PR also disables them for merge queue branches. These tests will still run on PRs, but not be ran on jobs triggered by the merge queue.
Unfortunately both GitHub Actions and Azure DevOps are unable to get the name of the PR branch that a merge queue branch was created from. If we wanted to selectively disable e2e tests for only `publish/` merge queue PRs, we would need to:
1. Check if the job is being ran for a GitHub merge queue branch (follows a common pattern)
2. Parse the PR number from the merge queue branch name
3. Query GitHub API PR metadata using the PR number
4. Check that the PR's head_ref starts with `publish/`
This would require using GitHub credentials but feels fragile if the GitHub merge queue …
> disable e2e tests for merge queue

- .chronus/changes/disable-no-unamed-types-2025-5-6-21-11-5.md
- packages/typespec-azure-rulesets/src/rulesets/data-plane.ts
- packages/typespec-azure-rulesets/src/rulesets/resource-manager.ts
Disabling the rule due to terrible performance just choking ide experience https://github.com/Azure/typespec-azure/issues/2803
> Disable no-unamed-types due to bad performance

- .chronus/changes/update-doc-2025-5-11-16-41-22.md
- packages/typespec-azure-core/lib/models.tsp
- website/src/content/docs/docs/libraries/azure-core/reference/data-types.md
It was reported that the doc was't up to date: https://github.com/Azure/typespec-azure/pull/2670#issuecomment-2954496245
> Update documenation about change from lower case to upper case to tenant and resourceGroup

- .chronus/changes/HEAD-2025-5-25-19-48-8.md
- packages/azure-http-specs/specs/azure/resource-manager/common-properties/mockapi.ts
- packages/azure-http-specs/specs/azure/resource-manager/large-header/main.tsp
`Request = void` effectively means `OptionalRequestBody = true`. 
Template default value is `false`:
https://github.com/Azure/typespec-azure/blob/88f4622ca3c09af9efce6dc38599a55063037186/packages/typespec-azure-resource-manager/lib/operations.tsp#L536
> [azure-http-specs] ARM case, fix large header action template

- .chronus/changes/fix-error-type-typo-2025-6-3-10-0-41.md
- packages/typespec-azure-resource-manager/lib/Legacy/operations.tsp
- website/src/content/docs/docs/libraries/azure-resource-manager/reference/interfaces.md
issue: https://github.com/Azure/typespec-azure/issues/2922
> Fix inconsistent `OverrideErrorType` parameter name across templates

- .chronus/changes/azure-http-specs_tcgc-override-2025-6-7-15-9-14.md
- packages/azure-http-specs/spec-summary.md
- packages/azure-http-specs/specs/azure/client-generator-core/override/client.tsp
- packages/azure-http-specs/specs/azure/client-generator-core/override/main.tsp
- packages/azure-http-specs/specs/azure/client-generator-core/override/mockapi.ts
Add test case for 2 applications of `@override` decorator.
1. reorder client method parameters
2. group parameters to a model (option bag) in client method
Reorder path parameters may be used to "mitigate the breaking changes" from the difference of path parameter order between Swagger (with inconsistent order) with TypeSpec (where path always follow the order in URL template),
Java supports this decorator (though may not have enabled it in ARM).
> azure-http-specs, add test case for tcgc override

- .github/scripts/validate-typespec-specs.ts
- .github/workflows/external-integration.yml
fix #2981 (Handle specs without main.tsp)
- Make the compile step fail but still run the git diff one so you can see all teh failing step and not assume the compile succeeded if there is git diff
- improve the logging in the compile step to make it easier to find errors
> Integration better checks

- .chronus/changes/fix_multipart-2025-6-18-15-33-1.md
- packages/typespec-client-generator-core/src/http.ts
- packages/typespec-client-generator-core/src/interfaces.ts
- packages/typespec-client-generator-core/src/internal-utils.ts
- packages/typespec-client-generator-core/src/public-utils.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/types/multipart.test.ts
This is a behavior breaking change. Currently, TCGC always replaces the property type of a multipart model with the real body type for the HTTP part. So, emitter could rely on the property type directly to serialize/deserialize an HTTP part. Also, the header parameters in one HTTP part are added to the `headers` property of `MultipartOptions` type.
For example:
```tsp
model MultiPartRequest {
stringWithContentType: HttpPart<{
@body body: string;
@header contentType: "text/html";
}>;
}
@post
op upload(
@header contentType: "multipart/form-data",
@multipartBody body: MultiPartRequest,
): void;
```
The type of `stringWithContentType` is `string` instead of an anonymous model `{@body body: string; @header contentType: "text/html";}` as before.
For any property with multipart serialization …
> [TCGC] Fix missing info for multipart cases after model property refactor

- .chronus/changes/fix_reinjection-2025-7-5-13-45-7.md
- packages/typespec-client-generator-core/src/methods.ts
- packages/typespec-client-generator-core/test/methods/paged-operation.test.ts
Fix: https://github.com/Azure/typespec-azure/issues/3115
> [TCGC] Fix next link re-injection segments missing problem after migrating to unbranded pagination.

- .chronus/changes/tcgc-mapping_fix-2025-7-21-17-40-53.md
- packages/typespec-client-generator-core/src/http.ts
- packages/typespec-client-generator-core/test/decorators/override.test.ts
- packages/typespec-client-generator-core/test/public-utils/get-http-operation-parameter.test.ts
This is a behavior breaking change. The Http parameter's corresponding parameter may change. It mostly happens in `@override` scenario. See the test change in the PR for the breaking change impact.
fix: https://github.com/Azure/typespec-azure/issues/3071
> [TCGC] Compare type when map body parameter to method parameter.

- website/src/content/current-sidebar.ts
- website/src/content/docs/docs/migrate-swagger/01-get-started.md
- website/src/content/docs/docs/migrate-swagger/checklists/migrate-arm-tips.md
- website/src/content/docs/docs/migrate-swagger/checklists/migrate-dp-tips.md
- website/src/content/docs/docs/migrate-swagger/faq/breakingchange.md
- website/src/content/docs/docs/migrate-swagger/faq/conversionfix.md
- website/src/content/docs/docs/migrate-swagger/faq/frequentquestions.md
- website/src/content/docs/docs/migrate-swagger/faq/mustread.md
- website/src/content/docs/docs/migrate-swagger/faq/pipeline.md
Swagger is a trademark of the company SmartBear and is generally deprecated as a spec name as Swagger is now used to refer to SmartBear's tooling.
Use OpenAPI instead.
> Rename swagger to OpenAPI

- .chronus/changes/tcgc-addDecoratorNamespace-2025-8-2-17-13-20.md
- packages/typespec-client-generator-core/src/interfaces.ts
- packages/typespec-client-generator-core/src/package.ts
- packages/typespec-client-generator-core/src/public-utils.ts
- packages/typespec-client-generator-core/test/decorators/general-list.test.ts
Since namespaces can be decorated with types, we want to pass these through if they exist
> [tcgc] add `.decorators` to `SdkNamespace`

- .chronus/changes/witemple-msft-tsp-autorest-xml-2025-8-17-14-15-26.md
- .gitmodules
- packages/samples/package.json
- packages/typespec-autorest/package.json
- packages/typespec-autorest/src/openapi.ts
- packages/typespec-autorest/src/openapi2-document.ts
- packages/typespec-autorest/src/xml.ts
- packages/typespec-autorest/test/parameters.test.ts
- packages/typespec-autorest/test/produces-consumes.test.ts
- packages/typespec-autorest/test/test-host.ts
- packages/typespec-autorest/test/xml.test.ts
- pnpm-lock.yaml
This PR adds support for XML metadata annotations to typespec-autorest:
- Changes the logic around top-level produces/consumes. It will now allow JSON or XML, rather than always using JSON only. If a service uses both, then it will pick both. It maintains the logic of only emitting operation-level produces/consumes if an operation differs from the top-level.
- Optionally depends on `@typespec/xml`. If it is not installed, all XML emit functionality is disabled.
- Emits `xml.name` for processed schemas if the XML name differs from the schema name.
- Emits `xml.namespace` and `xml.prefix` as needed.
- Emits `xml.attribute` for properties that are marked as attributes.
- Prefers XML names for properties if the service is only XML.
- Emits `x-ms-text` for properties that are `@unwrapped` if …
> [autorest] XML annotation support

- .chronus/changes/fix-rpc-operation-body-regression-2025-8-29-9-27-3.md
- packages/typespec-azure-core/src/rules/rpc-operation-request-body.ts
- packages/typespec-azure-core/test/rules/rpc-operation-request-body.test.ts
In the migration to tester v2 I removed the restriction that prevented this rule from running on non `Azure.` namespace which cause some failure in Azure batch client customization but then uncovered this rule didn't respect `@bodyIgnore`
> Fix Rpc operation request body regression

- .chronus/changes/main-2025-9-1-13-29-36.md
- .chronus/changes/witemple-msft-autorest-xml-strategy-2025-9-2-11-40-2.md
- packages/typespec-autorest-canonical/README.md
- packages/typespec-autorest-canonical/src/emitter.ts
- packages/typespec-autorest-canonical/src/lib.ts
- packages/typespec-autorest/README.md
- packages/typespec-autorest/src/emit.ts
- packages/typespec-autorest/src/lib.ts
- packages/typespec-autorest/src/openapi.ts
- packages/typespec-autorest/test/xml.test.ts
- website/src/content/docs/docs/emitters/typespec-autorest-canonical/reference/emitter.md
- website/src/content/docs/docs/emitters/typespec-autorest/reference/emitter.md
This PR adds an option for autorest XML emit that allows the project configuration to disable XML serialization annotations. This can be useful for some specifications that have operations that return raw XML payloads without polluting the whole spec with XML annotations. It also provides a point of extension in the future if more XML strategies are required.
> [autorest] XML emit strategy
