- packages/website/docusaurus.config.ts
https://tspwebsitepr.z22.web.core.windows.net/cadl-azure/prs/9/
> Add doc search

- eng/scripts/new_service_adoption.py
Redoing since there were issues with my first attempt.
> add comments and date range as arg

- common/changes/@azure-tools/typespec-autorest/hotfix-multipart-binary-parts_2023-12-13-22-29.json
- packages/typespec-autorest/src/openapi.ts
- packages/typespec-autorest/test/multipart.test.ts
> Hotfix: Multipart `bytes[]` part

- eng/scripts/new_service_adoption.py
Added support for various features that are useful for data gathering during mid-semester reviews. Also corrected what I think is an oversight in that the local repo was not using the same branch as the upstream query.
> various enhancements

- common/changes/@azure-tools/typespec-azure-core/azhang_filterCamelCase_2024-01-11-18-04.json
- docs/libraries/azure-core/reference/data-types.md
- docs/libraries/azure-core/reference/index.mdx
- packages/typespec-azure-core/lib/models.tsp
- packages/typespec-azure-core/src/rules/utils.ts
- packages/typespec-azure-core/test/rules/casing.test.ts
Added standard filter parameter model
> Relaxing camelCase casing rule to allow first non-alphabetic char,

- common/changes/@azure-tools/typespec-autorest/feature-encoded-name_2024-01-05-16-33.json
- packages/samples/test/output/core/encoded-names/@azure-tools/typespec-autorest/openapi.json
- packages/typespec-autorest/src/openapi.ts
- packages/typespec-autorest/test/models.test.ts
Core PR adding the decorator https://github.com/microsoft/typespec/pull/2779
> Add support for `@encodedName` in typespec-autorest

- common/changes/@azure-tools/typespec-client-generator-core/tcgc-encodedName_2024-01-08-20-01.json
- packages/typespec-client-generator-core/doc/types.tsp
- packages/typespec-client-generator-core/src/interfaces.ts
- packages/typespec-client-generator-core/src/public-utils.ts
- packages/typespec-client-generator-core/test/public-utils.test.ts
- packages/typespec-client-generator-core/test/types.test.ts
> [tcgc] add @encodedName support

- common/changes/@azure-tools/typespec-client-generator-core/fix_tcgc_issue_2024-01-12-09-48.json
- packages/typespec-client-generator-core/src/public-utils.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/types.test.ts
fix: https://github.com/Azure/typespec-azure/issues/119
fix: https://github.com/Azure/autorest.python/issues/2352
> Fix missing models when client hierarchy and naming issue for enum with projected name

- common/changes/@azure-tools/typespec-azure-resource-manager/fix-arm-common-version-on-enum-member_2024-01-22-21-54.json
- packages/typespec-azure-resource-manager/src/private.decorators.ts
- packages/typespec-azure-resource-manager/test/arm-common-versions.test.ts
- packages/typespec-azure-resource-manager/test/test-host.ts
> Fix: Resolve selected arm common version when used on version enum members

- docs/howtos/DataPlane Generation - DPG/03convenient.mdx
- docs/howtos/DataPlane Generation - DPG/04renaming.mdx
- docs/howtos/DataPlane Generation - DPG/05union.mdx
Fill in the Java part of how-to guide.
A few scenario is not supported right now, comment as such.
> java, update DPG how-to guide

- docs/howtos/ARM/change-provider-namespace.md
> Add how-to change provider namespace

- package.json
- pnpm-lock.yaml
Contains a fix around ignored packages that caused crash
> Update chronus 0.5.1

- .changeset/pink-steaks-matter.md
- packages/typespec-client-generator-core/src/interfaces.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/types.test.ts
fixes https://github.com/Azure/typespec-azure/issues/163
> [tcgc] remove primitive type consolidation

- packages/typespec-client-generator-core/CHANGELOG.md
- packages/typespec-client-generator-core/package.json
Tcgc had a change but seems like I forgot to add the changelog and so it didn't get bumped
> Missed some changelog and bumping of tcgc

- packages/website/docusaurus.config.ts
> Fix website playground icons

- .chronus/changes/unknown_format-2024-1-20-16-12-31.md
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/types.test.ts
> [tcgc] unknown format

- .chronus/changes/utc_info-2024-1-22-17-11-48.md
- packages/typespec-client-generator-core/src/interfaces.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/types.test.ts
> have separate datetime types

- .chronus/changes/update_doc-2024-1-18-15-55-46.md
- docs/libraries/typespec-client-generator-core/reference/decorators.md
- packages/typespec-client-generator-core/README.md
- packages/typespec-client-generator-core/lib/decorators.tsp
> update doc for `@usage` and `@access`

- .chronus/changes/add_operation_status-2024-1-23-16-6-53.md
- .chronus/changes/roll_back_envelope_arm-2024-1-26-14-26-53.md
- packages/typespec-client-generator-core/src/types.ts
Rolling back fix for arm bc of a separate issue in arm https://github.com/Azure/typespec-azure/issues/311
> [tcgc] avoid duplicate model generation for arm lro

- .chronus/changes/enum-value-type-2024-2-5-16-25-35.md
- packages/typespec-client-generator-core/src/public-utils.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/types.test.ts
fix: https://github.com/Azure/typespec-azure/issues/353
> Enhance logic for value type of enum and union as enum for TCGC

- .chronus/changes/add_versions_enum-2024-2-7-16-59-10.md
- .chronus/changes/fix_etag-2024-2-5-12-2-26.md
- docs/howtos/DataPlane Generation - DPG/06types.mdx
- packages/typespec-client-generator-core/src/interfaces.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/public-utils.test.ts
- packages/typespec-client-generator-core/test/types.test.ts
> [tcgc] return Versions enum used in versioning

- .chronus/changes/discriminator-property-2024-2-12-14-10-27.md
- packages/typespec-client-generator-core/doc/types.tsp
- packages/typespec-client-generator-core/src/interfaces.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/types.test.ts
resolve: https://github.com/Azure/typespec-azure/issues/291
> add `discriminatorProperty` ref to discriminated model

- .chronus/changes/azhang_updateAzureCoreVersionDependency-2024-2-21-1-2-49.md
- eng/feeds/arm/main.tsp
- eng/feeds/data-plane/main.tsp
- packages/samples/specs/data-plane/api-path-parameter/main.tsp
- packages/samples/specs/data-plane/azure-core-scalars/main.tsp
- packages/samples/specs/data-plane/custom-error-type/main.tsp
- packages/samples/specs/data-plane/formrecognizer/main.tsp
- packages/samples/specs/resource-manager/arm-scenarios/operation-status/main.tsp
- packages/samples/specs/resource-manager/operationsTest/main.tsp
- packages/typespec-azure-resource-manager/lib/arm.tsp
https://github.com/microsoft/typespec/issues/3037
> Updating Azure.Core version dependency to Preview_2

- .chronus/changes/enableCommonTypesRule-2024-3-1-19-59-35.md
- packages/typespec-azure-resource-manager/src/linter.ts
Closes: https://github.com/Azure/typespec-azure-pr/issues/3839
**REST API Specs** (1 violation)
https://github.com/Azure/azure-rest-api-specs/pull/28547
> Enable common-types rule by default.

- docs/getstarted/createproject.md
Edited for clarity and updated to include descriptions for all four current templates.
> edit and update of createproject.md

- packages/typespec-azure-playground-website/package.json
- packages/typespec-azure-playground-website/samples/arm.tsp
- packages/typespec-azure-playground-website/samples/azure-core.tsp
- packages/typespec-azure-playground-website/samples/build.js
- packages/typespec-azure-playground-website/samples/tspconfig.yaml
- packages/typespec-azure-playground-website/test/validate-samples.test.ts
- packages/typespec-azure-playground-website/tsconfig.json
Needs https://github.com/microsoft/typespec/pull/3124
> Verify samples against linters

- .chronus/changes/fix_orphan-2024-3-7-15-59-24.md
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/types.test.ts
> fix orphan union as enum has no usage problem

- .chronus/changes/remove_error_throwing-2024-3-8-14-34-21.md
- packages/typespec-client-generator-core/lib/main.tsp
- packages/typespec-client-generator-core/src/decorators.ts
- packages/typespec-client-generator-core/src/http.ts
- packages/typespec-client-generator-core/src/interfaces.ts
- packages/typespec-client-generator-core/src/internal-utils.ts
- packages/typespec-client-generator-core/src/lib.ts
- packages/typespec-client-generator-core/src/package.ts
- packages/typespec-client-generator-core/src/public-utils.ts
- packages/typespec-client-generator-core/test/public-utils.test.ts
- packages/typespec-client-generator-core/test/types.test.ts
> [tcgc] unify error throwing to use the diagnostics infrastructure

- docs/howtos/DataPlane Generation - DPG/08methodInputs.mdx
fix https://github.com/Azure/autorest.java/issues/2678
> [tcgc] Method Input Signatures Doc - Java

- .chronus/changes/fix_tcgc_go_issue-2024-3-9-16-28-52.md
- packages/typespec-client-generator-core/src/public-utils.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/public-utils.test.ts
- packages/typespec-client-generator-core/test/types.test.ts
fix: https://github.com/Azure/typespec-azure/issues/629
fix: https://github.com/Azure/typespec-azure/issues/632
> fix cross language definition id issue

- .chronus/changes/fix_wire_type_nullable-2024-3-11-16-10-51.md
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/types.test.ts
> fix wire type nullable info

- .chronus/changes/fix_mapping-2024-3-11-22-13-20.md
- packages/typespec-client-generator-core/src/package.ts
- packages/typespec-client-generator-core/test/package.test.ts
- packages/typespec-client-generator-core/test/types.test.ts
Use http operation when generating service method parameters.
> change service method parameter impl

- .chronus/changes/upgrade-deps-april-2024-2024-3-13-20-12-36.md
- .chronus/config.yaml
- package.json
- packages/e2e-tests/package.json
- packages/samples/package.json
- packages/typespec-autorest-canonical/package.json
- packages/typespec-autorest/package.json
- packages/typespec-azure-core/package.json
- packages/typespec-azure-playground-website/package.json
- packages/typespec-azure-portal-core/package.json
- packages/typespec-azure-resource-manager/package.json
- packages/typespec-client-generator-core/package.json
- packages/typespec-service-csharp/package.json
- packages/website/package.json
- pnpm-lock.yaml
fix https://github.com/microsoft/typespec/pull/3169
> Upgrade dependencies - april 2024

- .vscode/tasks.json
fix https://github.com/Azure/typespec-azure/issues/695
> Fix watch-source vscode task

- docs/howtos/DataPlane Generation - DPG/06types.mdx
Fix https://github.com/Azure/typespec-azure/issues/633
> Add flattenProperty in the doc

- .chronus/changes/fix_array-2024-3-18-17-41-54.md
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/types.test.ts
@iscai-msft please help to review and release, thanks.
fix: https://github.com/Azure/typespec-azure/issues/690
cc: @haolingdong-msft
> fix wrong judgement for array type

- .chronus/changes/export_more_api-2024-3-23-17-29-45.md
- packages/typespec-client-generator-core/src/interfaces.ts
> [tcgc] export int and float type judgement function

- .chronus/changes/fix_clientname-2024-3-24-17-43-5.md
- packages/typespec-client-generator-core/src/decorators.ts
- packages/typespec-client-generator-core/test/decorators.test.ts
fixes https://github.com/Azure/typespec-azure/issues/730
> [tcgc] fix @clientName lost after adding versioning support

- packages/typespec-client-generator-core/test/decorators.test.ts
add test for: https://github.com/Azure/typespec-azure/issues/699#event-12593890119
> [tcgc] add test for `@clientName` on templated parameter

- docs/getstarted/azure-resource-manager/step02.md
- docs/getstarted/azure-resource-manager/step03.md
- docs/getstarted/azure-resource-manager/step04.md
- docs/getstarted/azure-resource-manager/step05.md
- packages/typespec-azure-playground-website/samples/arm.tsp
for `ResourceNameParameter` to be available.
> Temporarily restore playground sample until next release 

- docs/howtos/DataPlane Generation - DPG/06types.mdx
> add csharp additional properties document

- .chronus/changes/fix_usage_propagation-2024-3-28-14-42-20.md
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/types.test.ts
fix: https://github.com/Azure/typespec-azure/issues/752
> [tcgc] fix usage propagation from sub types

- .chronus/changes/fix-allow-scalars-2024-3-26-23-13-19.md
- packages/typespec-azure-resource-manager/src/rules/arm-resource-name-pattern.ts
- packages/typespec-azure-resource-manager/test/rules/arm-resource-name-pattern.test.ts
fix [#732](https://github.com/Azure/typespec-azure/issues/732)
> Allow @pattern to be provided on a scalar

- .chronus/changes/fix_duplication-2024-4-6-18-11-9.md
- packages/typespec-client-generator-core/src/http.ts
- packages/typespec-client-generator-core/src/internal-utils.ts
- packages/typespec-client-generator-core/test/package.test.ts
> fix duplicated content type parameter for rpc lro

- .chronus/changes/fix_default_api_version-2024-4-7-14-54-37.md
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/package.test.ts
> fix wrong default version for interface from extends

- .chronus/changes/tcgc_fix_api_version-2024-4-8-16-21-13.md
- packages/typespec-client-generator-core/src/public-utils.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/decorators.test.ts
- packages/typespec-client-generator-core/test/public-utils.test.ts
- packages/typespec-client-generator-core/test/types.test.ts
resolve: https://github.com/Azure/typespec-azure/issues/746
> [tcgc] `getDefaultApiVersion` and service version enum hornor api version config

- .chronus/changes/fix-response-body-type-2024-4-9-11-14-24.md
- packages/typespec-client-generator-core/src/http.ts
- packages/typespec-client-generator-core/test/package.test.ts
fixes https://github.com/Azure/typespec-azure/issues/800
> [TCGC] Fix error response when error model has status code

- docs/howtos/DataPlane Generation - DPG/06types.mdx
> feat(doc): update csharp support for @flattenProperty

- .chronus/changes/main-2024-4-11-15-5-45.md
- .chronus/changes/main-2024-4-11-15-7-31.md
- packages/typespec-client-generator-core/src/public-utils.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/package.test.ts
- packages/typespec-client-generator-core/test/public-utils.test.ts
resolve: https://github.com/Azure/autorest.go/issues/1304
> [tcgc] fix two issues found by go mpg

- .chronus/changes/fix_value_discriminator-2024-4-15-10-46-20.md
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/types.test.ts
fix: https://github.com/Azure/autorest.go/issues/1206
> [tcgc] map discriminator string value type to enum value type

- .chronus/changes/discriminator_doc-2024-4-21-11-13-50.md
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/types.test.ts
fix: https://github.com/Azure/typespec-azure/issues/872
> [tcgc] add description for created discriminator property

- .chronus/changes/constant_generated_name-2024-4-22-16-8-23.md
- packages/typespec-client-generator-core/src/public-utils.ts
- packages/typespec-client-generator-core/test/types.test.ts
> [tcgc] don't add constant value to generated name

- .chronus/changes/update-rulesets-in-templates-2024-4-23-17-47-34.md
- eng/feeds/arm-canonical/tspconfig.yaml
- eng/feeds/arm/tspconfig.yaml
- eng/feeds/arm/tspconfig_stand_alone.yaml
- eng/feeds/data-plane/tspconfig.yaml
- packages/typespec-azure-playground-website/package.json
- packages/typespec-azure-playground-website/samples/build.js
- packages/typespec-azure-playground-website/src/index.ts
- packages/typespec-azure-rulesets/package.json
- packages/website/package.json
- pnpm-lock.yaml
> Update rulesets in templates

- .chronus/changes/usage_refine-2024-4-29-22-20-25.md
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/types.test.ts
fix: https://github.com/Azure/typespec-azure/issues/916
> [tcgc] add read only logic to usage propagation

- .chronus/changes/fix-arm-id-2024-5-18-17-30-45.md
- packages/typespec-client-generator-core/src/interfaces.ts
- packages/typespec-client-generator-core/test/types/built-in-types.test.ts
resolves https://github.com/Azure/typespec-azure/issues/1031
> Set armId kind for Azure.Core.armResourceIdentifier

- .chronus/changes/export_sdkmethod-2024-5-12-13-43-49.md
- packages/typespec-client-generator-core/src/interfaces.ts
fix: https://github.com/Azure/typespec-azure/issues/969
> export `SdkClientAccessor`

- .chronus/changes/content_types_not_empty-2024-5-24-16-39-12.md
- packages/typespec-client-generator-core/src/http.ts
- packages/typespec-client-generator-core/test/package.test.ts
> [tcgc] don't set optional `.contentTypes` property on responses to an empty list

- .chronus/changes/azhang_fixingTyppo-2024-6-1-11-53-0.md
- docs/getstarted/azure-resource-manager/step04.md
- packages/typespec-azure-resource-manager/src/rules/arm-resource-name-pattern.ts
- packages/typespec-client-generator-core/doc/types.tsp
> Fixing typpo

- .chronus/changes/tcgc-header-content-type-2024-6-2-17-33-49.md
- packages/typespec-client-generator-core/src/http.ts
- packages/typespec-client-generator-core/src/internal-utils.ts
- packages/typespec-client-generator-core/src/public-utils.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/types/response.test.ts
fixes https://github.com/Azure/typespec-azure/issues/1112
> [Tcgc] add `content-type` in response headers

- .chronus/changes/azhang_ArmResourceListByParentOpId-2024-5-27-17-25-9.md
- packages/samples/specs/resource-manager/resource-common-properties/private-links/main.tsp
- packages/samples/specs/resource-manager/resource-types/location/main.tsp
- packages/samples/specs/resource-manager/resource-types/singleton/main.tsp
- packages/samples/specs/resource-manager/resource-types/tenant/main.tsp
- packages/samples/specs/resource-manager/resource-types/virtual-resource/main.tsp
- packages/samples/test/output/azure/resource-manager/arm-library/@azure-tools/typespec-autorest/openapi.json
- packages/samples/test/output/azure/resource-manager/legacy/managed-identity/@azure-tools/typespec-autorest/2023-03-01-preview/openapi.json
- packages/samples/test/output/azure/resource-manager/operations/nobody-action/@azure-tools/typespec-autorest/2021-10-01-preview/openapi.json
- packages/samples/test/output/azure/resource-manager/resource-common-properties/common-properties/@azure-tools/typespec-autorest/2023-03-01-preview/openapi.json
- packages/samples/test/output/azure/resource-manager/resource-common-properties/encryption/@azure-tools/typespec-autorest/2023-03-01-preview/openapi.json
- packages/samples/test/output/azure/resource-manager/resource-common-properties/managed-identity/@azure-tools/typespec-autorest/2023-03-01-preview/openapi.json
- packages/samples/test/output/azure/resource-manager/resource-types/extension/@azure-tools/typespec-autorest/2021-10-01-preview/openapi.json
- packages/samples/test/output/azure/resource-manager/resource-types/location/@azure-tools/typespec-autorest/2021-10-01-preview/openapi.json
- packages/samples/test/output/azure/resource-manager/resource-types/proxy/@azure-tools/typespec-autorest/2021-10-01-preview/openapi.json
- packages/samples/test/output/azure/resource-manager/resource-types/singleton/@azure-tools/typespec-autorest/2021-10-01-preview/openapi.json
- packages/samples/test/output/azure/resource-manager/resource-types/tenant/@azure-tools/typespec-autorest/2021-10-01-preview/openapi.json
- packages/samples/test/output/azure/resource-manager/resource-types/tracked/@azure-tools/typespec-autorest/2021-10-01-preview/openapi.json
- packages/samples/test/output/azure/resource-manager/resource-types/virtual-resource/@azure-tools/typespec-autorest/2021-10-01-preview/openapi.json
- packages/typespec-azure-resource-manager/lib/interfaces.tsp
- packages/typespec-azure-resource-manager/lib/operations.tsp
> Removing $armRenameListByOperation decorator so operation id is directly derived from op name

- .chronus/changes/fix_multi_call-2024-6-4-14-14-39.md
- .chronus/changes/fix_multi_call-2024-6-4-14-14-52.md
- .chronus/changes/fix_multi_call-2024-6-4-14-15-0.md
- .chronus/changes/fix_multi_call-2024-6-4-14-15-19.md
- .chronus/changes/fix_multi_call-2024-6-4-14-15-29.md
- .chronus/changes/fix_multi_call-2024-6-4-14-15-37.md
- .chronus/changes/fix_multi_call-2024-6-4-14-15-45.md
- .chronus/changes/fix_multi_call-2024-6-4-14-15-9.md
- .chronus/changes/main-2024-6-3-20-41-58.md
- packages/typespec-client-generator-core/package.json
- packages/typespec-client-generator-core/src/decorators.ts
- packages/typespec-client-generator-core/test/decorators.test.ts
fix: https://github.com/Azure/typespec-azure/issues/1109
> [tcgc] fix wrong client resolving from multiple call of context creation for versioning tsp

- .chronus/changes/fix_one_variant_union-2024-6-9-14-12-37.md
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/types/union-types.test.ts
resolve: https://github.com/Azure/typespec-azure/issues/1134
> fix wrong handling for one variant union

- .chronus/changes/add_exception_usage-2024-5-24-15-52-13.md
- .chronus/changes/decorators_list-2024-5-6-18-38-7.md
- .chronus/changes/fix_decorator_list-2024-5-26-13-53-0.md
- .chronus/changes/fix_multi_call-2024-6-4-14-14-39.md
- .chronus/changes/fix_multi_call-2024-6-4-14-14-52.md
- .chronus/changes/fix_multi_call-2024-6-4-14-15-0.md
- .chronus/changes/fix_multi_call-2024-6-4-14-15-19.md
- .chronus/changes/fix_multi_call-2024-6-4-14-15-29.md
- .chronus/changes/fix_multi_call-2024-6-4-14-15-37.md
- .chronus/changes/fix_multi_call-2024-6-4-14-15-45.md
- .chronus/changes/fix_multi_call-2024-6-4-14-15-48.md
- .chronus/changes/fix_multi_call-2024-6-4-14-15-9.md
- .chronus/changes/fix_one_variant_union-2024-6-9-14-12-37.md
- .chronus/changes/main-2024-6-3-20-41-58.md
- .chronus/changes/new_spread-2024-4-23-14-11-6.md
- .chronus/changes/remove-tspnamespace-add-crosslanguagedefinitionid-2024-5-25-16-6-39.md
- .chronus/changes/rename_datetime_type-2024-5-24-14-52-19.md
- .chronus/changes/tcgc-header-content-type-2024-6-2-17-33-49.md
- packages/typespec-client-generator-core/CHANGELOG.md
- packages/typespec-client-generator-core/package.json
> tcgc hotfix release

- docs/howtos/DataPlane Generation - DPG/08methodInputs.mdx
target https://github.com/Azure/typespec-azure/pull/1092
0.18.0 released and merged into SDK repo
> [DPG] spread doc, java

- .chronus/changes/add_protocol_convenient-2024-6-11-13-26-58.md
- packages/typespec-client-generator-core/src/interfaces.ts
- packages/typespec-client-generator-core/src/package.ts
- packages/typespec-client-generator-core/test/decorators.test.ts
> [tcgc] add `.generateProtocol` and `.generateConvenient` to service methods

- .chronus/changes/azhang_ArmCommonTypeFix-2024-6-11-17-27-33.md
- docs/libraries/azure-resource-manager/reference/data-types.md
- packages/samples/common-types/openapi/v3/types.json
- packages/samples/common-types/openapi/v4/types.json
- packages/samples/common-types/openapi/v5/types.json
- packages/samples/test/output/azure/resource-manager/arm-library/@azure-tools/typespec-autorest/openapi.json
- packages/samples/test/output/azure/resource-manager/contoso/@azure-tools/typespec-autorest/openapi.json
- packages/samples/test/output/azure/resource-manager/operations/nobody-action/@azure-tools/typespec-autorest/2021-10-01-preview/openapi.json
- packages/samples/test/output/azure/resource-manager/resource-types/extension/@azure-tools/typespec-autorest/2021-10-01-preview/openapi.json
- packages/samples/test/output/azure/resource-manager/resource-types/location/@azure-tools/typespec-autorest/2021-10-01-preview/openapi.json
- packages/samples/test/output/azure/resource-manager/resource-types/proxy/@azure-tools/typespec-autorest/2021-10-01-preview/openapi.json
- packages/samples/test/output/azure/resource-manager/resource-types/singleton/@azure-tools/typespec-autorest/2021-10-01-preview/openapi.json
- packages/samples/test/output/azure/resource-manager/resource-types/tenant/@azure-tools/typespec-autorest/2021-10-01-preview/openapi.json
- packages/samples/test/output/azure/resource-manager/resource-types/tracked/@azure-tools/typespec-autorest/2021-10-01-preview/openapi.json
- packages/samples/test/output/azure/resource-manager/resource-types/virtual-resource/@azure-tools/typespec-autorest/2021-10-01-preview/openapi.json
- packages/typespec-azure-resource-manager/lib/common-types/types.tsp
- packages/typespec-azure-resource-manager/lib/foundations/arm.foundations.tsp
> Minor fix of ARM common type and foundations

- .chronus/changes/fix_spread-2024-6-17-15-41-11.md
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/package.test.ts
fix: https://github.com/Azure/typespec-azure/issues/1184
> [tcgc] fix idempotent issue for spread

- .chronus/changes/fix-spread-access-2024-6-17-17-19-45.md
- .chronus/changes/fix_spread-2024-6-17-15-41-11.md
- .chronus/changes/throw-client-name-conflicts-2024-6-5-13-7-58.md
- packages/typespec-client-generator-core/CHANGELOG.md
- packages/typespec-client-generator-core/package.json
hotfix for spread usage and access calculation issue
> release tcgc 0.44.1

- .chronus/changes/namespace_client_name-2024-6-18-19-15-52.md
- packages/typespec-client-generator-core/src/package.ts
- packages/typespec-client-generator-core/test/decorators.test.ts
> [tcgc] fix @clientName with @operationGroup

- .chronus/changes/regen-signatures-with-new-interface-2024-6-22-15-40-4.md
- docs/libraries/azure-core/reference/data-types.md
- docs/libraries/azure-resource-manager/reference/data-types.md
- packages/typespec-azure-core/generated-defs/Azure.Core.Foundations.Private.ts
- packages/typespec-azure-resource-manager/generated-defs/Azure.ResourceManager.CommonTypes.Private.ts
- packages/typespec-azure-resource-manager/generated-defs/Azure.ResourceManager.ts
- packages/typespec-azure-resource-manager/src/common-types.ts
- packages/typespec-azure-resource-manager/src/commontypes.private.decorators.ts
Blocked on https://github.com/microsoft/typespec/pull/3929
> Regen signatures with new interface

- .chronus/changes/operation-validation-2024-6-19-18-35-46.md
- .chronus/changes/revert-fix-2024-6-23-10-47-25.md
- packages/typespec-client-generator-core/src/validate.ts
- packages/typespec-client-generator-core/test/decorators.test.ts
Revert the fix from main, and apply it to release branch to align with the release git flow.
> Revert "fix `@clientName` validation for operation within interface"

- .chronus/changes/no_server_desc-2024-6-29-14-27-45.md
- packages/typespec-client-generator-core/src/package.ts
- packages/typespec-client-generator-core/test/package.test.ts
> [tcgc] don't move server description onto endpoints

- .chronus/changes/enable-friendly-name-rule-2024-6-17-15-14-50.md
- packages/typespec-azure-rulesets/src/rulesets/data-plane.ts
- packages/typespec-azure-rulesets/src/rulesets/resource-manager.ts
> Enable friendly name rule

- .chronus/changes/union_template_args-2024-7-9-16-20-13.md
- packages/typespec-client-generator-core/src/interfaces.ts
- packages/typespec-client-generator-core/src/package.ts
- packages/typespec-client-generator-core/src/types.ts
> [tcgc] add optional generic parameters to `SdkUnionType`

- .chronus/changes/example_dir_default-2024-7-16-10-57-36.md
- packages/typespec-client-generator-core/src/example.ts
- packages/typespec-client-generator-core/test/examples/load.test.ts
sync logic from https://github.com/Azure/typespec-azure/pull/1368
> [tcgc] add default path for example detection

- docs/howtos/DataPlane Generation - DPG/06types.mdx
link https://github.com/Azure/autorest.java/issues/2863
feature would be in next release (0.19.2)
```
@encode(string)
prop: int64;
```
> docs, DPG how-to, java on encode string

- .chronus/changes/remove_deprecated_thing-2024-7-26-14-46-54.md
- docs/libraries/typespec-client-generator-core/reference/decorators.md
- docs/libraries/typespec-client-generator-core/reference/index.mdx
- packages/typespec-client-generator-core/README.md
- packages/typespec-client-generator-core/generated-defs/Azure.ClientGenerator.Core.ts
- packages/typespec-client-generator-core/lib/decorators.tsp
- packages/typespec-client-generator-core/src/decorators.ts
- packages/typespec-client-generator-core/src/interfaces.ts
- packages/typespec-client-generator-core/src/package.ts
- packages/typespec-client-generator-core/src/public-utils.ts
- packages/typespec-client-generator-core/src/tsp-index.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/decorators.test.ts
resolve: https://github.com/Azure/typespec-azure/issues/1080
> [tcgc] clean up deprecation exports of previous version

- .chronus/changes/spread_version_projection-2024-7-27-15-27-23.md
- packages/typespec-client-generator-core/src/http.ts
- packages/typespec-client-generator-core/src/internal-utils.ts
- packages/typespec-client-generator-core/src/public-utils.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/packages/spread.test.ts
fix: https://github.com/Azure/typespec-azure/issues/1429
> [tcgc] need to handle projection when finding spread original model

- .chronus/changes/fix_example_load-2024-7-27-14-24-44.md
- packages/typespec-client-generator-core/src/example.ts
- packages/typespec-client-generator-core/test/examples/http-operation-examples.test.ts
- packages/typespec-client-generator-core/test/examples/http-operation-examples/bodyFallback.json
- packages/typespec-client-generator-core/test/examples/load.test.ts
- packages/typespec-client-generator-core/test/examples/load/clientName.json
- packages/typespec-client-generator-core/test/examples/load/clientNameAnother.json
fix: https://github.com/Azure/typespec-azure/issues/1430
> [tcgc] consider renaming when mapping examples

- docs/howtos/Client Generation/00howtogen.mdx
Some sentences in the doc is a bit difficult to understand.
Fix some grammar issue and leverage copilot to make the information to be clearer.
> Update the doc of DPG guide on  'How to generate client libraries'.

- .chronus/changes/paging-item-name-2024-7-29-17-10-10.md
- packages/typespec-autorest/src/openapi.ts
- packages/typespec-autorest/src/openapi2-document.ts
- packages/typespec-autorest/test/paging.test.ts
> Add support for custom item name

- .chronus/changes/tcgc-lro-metadata-2024-8-11-22-30-34.md
- packages/typespec-client-generator-core/src/interfaces.ts
- packages/typespec-client-generator-core/src/package.ts
- packages/typespec-client-generator-core/test/methods/lro.test.ts
- add `SdkLroServiceMetadata` and corresponding LRO metadata
- update LRO metadata initialization lgoic
- add test cases
resolve #1236
> feat(tcgc): add `SdkLroServiceMetadata`

- .chronus/changes/fix-tcgc-subid-2024-8-14-13-38-41.md
- packages/typespec-client-generator-core/src/package.ts
- packages/typespec-client-generator-core/test/package.test.ts
fix lack of `subscription_id` of ARM SDK: https://github.com/Azure/azure-sdk-for-python/pull/37391/files#diff-6379cca2979bbcd25ca1a5e57303245925f770044d42a36754334a5e22f8e0e4
> [TCGC] Fix `subscriptionId` for ARM SDK

- docs/howtos/Client Generation/07tcgcTypes.mdx
Fixes https://github.com/Azure/typespec-azure/issues/1260
> refine the document for `SdkBuiltInType`

- packages/azure-http-specs/package.json
- packages/azure-http-specs/spec-summary.md
This is the `typespec-azure` counterpart of the PR https://github.com/microsoft/typespec/pull/4768. 
I have compared the generated file with the file in the `cadl-ranch` summary and confirmed that it is exactly the same.
Please review and approve the PR. Thanks
> [@azure-tools/azure-http-specs] Added Spec Summary

- .chronus/changes/RollOutAzureHttpSpecsII-2024-9-29-10-42-31.md
- packages/azure-http-specs/package.json
This is the azure specific counter part of the PR https://github.com/microsoft/typespec/pull/4836. In this PR, the `azure-http-specs` package is being rolled out. 
Please review and approve the PR. Thanks
> [@azure-tools/azure-http-specs] - Rollout the azure http specs package

- eng/pipelines/ci.yml
- eng/pipelines/jobs/website.yml
- package.json
- pnpm-lock.yaml
Same pr as typespec core https://github.com/microsoft/typespec/pull/4994
> Dedicated job for website ci

- CONTRIBUTING.md
Updating documentation: https://github.com/Azure/typespec-azure/blob/main/CONTRIBUTING.md#testing-a-change-in-repo-azure-rest-api-specs
I did this process recently: https://github.com/Azure/azure-rest-api-specs/pull/31352/files
> Update documentation for testing a change in repo azure-rest-api-specs

- .chronus/changes/add_page_helper-2024-10-11-17-51-49.md
- packages/typespec-client-generator-core/src/public-utils.ts
- packages/typespec-client-generator-core/test/public-utils/is-paged-result-model.test.ts
resolve: https://github.com/Azure/typespec-azure/issues/1464
> [tcgc] add `isPagedResultModel` helper function

- .chronus/changes/fix_usage-2024-10-11-16-1-31.md
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/packages/responses.test.ts
fix: https://github.com/Azure/typespec-azure/issues/1748
> [tcgc] do not add protocol usage for protocol method's response type

- .chronus/changes/azure-http-specs_fix-singleton-patch-2024-10-25-16-32-50.md
- packages/azure-http-specs/spec-summary.md
- packages/azure-http-specs/specs/azure/resource-manager/resources/mockapi.ts
- packages/azure-http-specs/specs/azure/resource-manager/resources/singleton.tsp
A missed backport from cadl-ranch https://github.com/Azure/cadl-ranch/pull/759
> azure-http-specs, fix singleton patch

- .chronus/changes/AzureSpecsAlpha2-2024-10-26-16-12-19.md
- packages/azure-http-specs/CHANGELOG.md
- packages/azure-http-specs/package.json
> [@azure-tools/azure-http-specs] - Release Alpha 2 Version

- .chronus/changes/remove_visibility_none-2024-10-27-11-57-7.md
- packages/typespec-client-generator-core/src/public-utils.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/packages/responses.test.ts
- packages/typespec-client-generator-core/test/types/model-types.test.ts
fix: https://github.com/Azure/typespec-azure/issues/1916
> [tcgc] remove none visibility property for model

- website/src/content/docs/docs/howtos/Generate client libraries/12multipart.mdx
- add csharp part of Multipart document
> add Multipart document in .Net SDK

- website/src/content/docs/docs/howtos/Generate client libraries/02client.mdx
Add java doc for https://github.com/Azure/typespec-azure/pull/1945
> add client initialization docs - java doc

- website/src/content/docs/docs/release-notes/release-2024-12-10.mdx
Add Release notes for December release
> Release notes for 2024 December release

- eng/pipelines/deploy-azure-spec-dashboard-storage-account.yml
- packages/azure-spec-dashboard/src/apis.ts
Please review and approve the PR. Thanks
Note: Tested the changes [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4421102&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=4fc2278e-dafd-525f-7501-d396c9a4758e)
> Fix Dashboard release pipeline

- .chronus/changes/fix_example_order-2024-11-18-20-58-12.md
- packages/typespec-client-generator-core/src/example.ts
- packages/typespec-client-generator-core/test/examples/load.test.ts
- packages/typespec-client-generator-core/test/examples/load/a.json
- packages/typespec-client-generator-core/test/examples/load/a_b.json
- packages/typespec-client-generator-core/test/examples/load/a_b_c.json
fix: https://github.com/Azure/typespec-azure/issues/1986
> [tcgc] ensure operation examples to be ordered

- .chronus/changes/fix_page-2024-11-19-11-42-25.md
- packages/typespec-client-generator-core/src/package.ts
- packages/typespec-client-generator-core/test/packages/paged-operation.test.ts
fix: https://github.com/Azure/typespec-azure/issues/1985
> [tcgc] get correct pageable info for azure pageable operation with inheritance return model

- .github/policies/issues.triage.generated.yml
- .github/policies/prs.triage.generated.yml
- CONTRIBUTING.md
Unblock: https://github.com/Azure/typespec-azure/pull/1202
> Update contributing labels

- packages/azure-spec-dashboard/src/apis.ts
Contributes to https://github.com/Azure/azure-sdk-for-net/issues/47071
> add new csharp emitter

- packages/azure-spec-dashboard/CHANGELOG.md
- packages/azure-spec-dashboard/README.md
- packages/azure-spec-dashboard/index.html
- packages/azure-spec-dashboard/package.json
Rename Title to Azure Spector Dashboard
> [@azure-tools/azure-spec-dashboard]  - Rename Title to Azure Spector Dashboard

- .chronus/changes/add_nullable_name-2025-0-20-17-36-45.md
- packages/typespec-client-generator-core/src/interfaces.ts
- packages/typespec-client-generator-core/src/package.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/types/union-types.test.ts
fix: https://github.com/Azure/typespec-azure/issues/2088
> [tcgc] support `name` and `isGeneratedName` for nullable type

- website/src/content/docs/docs/howtos/Generate client libraries/02client.mdx
- website/src/content/docs/docs/howtos/Generate client libraries/06types.mdx
1. add sub namespace example for clients
2. add sub namespace example for models
3. rearrange the sections
> [doc] update namespace related docs

- eng/pipelines/publish.yml
Upload Manifest based on azure specs publish
> Upload Manifest based on azure specs publish

- .chronus/changes/fix-arm-provider-async-2025-0-29-17-16-45.md
- packages/typespec-azure-resource-manager/lib/operations.tsp
fix issue: https://github.com/Azure/typespec-azure/issues/2064
> Fix Provider name is not replaced in the route 

- .chronus/changes/tcgc-visibilityHeader-2025-1-3-16-4-24.md
- packages/typespec-client-generator-core/src/interfaces.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/types/model-types.test.ts
fixes https://github.com/Azure/typespec-azure/issues/2122
> [tcgc] add visibility to non-body properties

- .chronus/changes/clientNameXMsEnum-2025-0-27-14-20-31.md
- packages/typespec-autorest/src/openapi.ts
- packages/typespec-autorest/test/openapi-output.test.ts
- pnpm-lock.yaml
> Autorest: Propagate @clientName to x-ms-enum.name for enums and unions

- .github/workflows/website-gh-pages.yml
Same as https://github.com/microsoft/typespec/pull/5881
> fix website publish

- .chronus/changes/tcgc-fixVisiblityCall-2025-1-5-14-41-46.md
- packages/typespec-client-generator-core/src/internal-utils.ts
- packages/typespec-client-generator-core/src/public-utils.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/packages/responses.test.ts
- packages/typespec-client-generator-core/test/types/model-types.test.ts
> [tcgc] switch to `getLifecycleVisibilityEnum` call from deprecated `getVisibility`

- CONTRIBUTING.md
This PR updates the publishing steps based on differences I saw when running last month's release.
> update publishing steps

- .chronus/changes/tcgc-fixRegression-2025-1-12-13-30-13.md
- packages/typespec-client-generator-core/src/types.ts
> [tcgc] fix orphan model regression

- packages/samples/specs/resource-manager/common-types/v3/types.json
- packages/samples/specs/resource-manager/common-types/v4/managedidentity.json
- packages/samples/specs/resource-manager/common-types/v4/privatelinks.json
- packages/samples/specs/resource-manager/common-types/v4/types.json
- packages/samples/specs/resource-manager/common-types/v5/customermanagedkeys.json
- packages/samples/specs/resource-manager/common-types/v5/managedidentity.json
- packages/samples/specs/resource-manager/common-types/v5/privatelinks.json
- packages/samples/specs/resource-manager/common-types/v5/types.json
I need to update the common-types of the specs as I updated them on azure-rest-api-specs: https://github.com/Azure/azure-rest-api-specs/pull/32574
> Sync common types after sorting 

- website/src/content/docs/docs/howtos/Generate client libraries/10longRunningOperations.mdx
Make each block a complete TypeSpec sample.
> docs, howto, improve Azure LRO doc

- .chronus/changes/refine_typing-2025-1-14-10-54-42.md
- packages/typespec-client-generator-core/src/decorators.ts
- packages/typespec-client-generator-core/src/http.ts
- packages/typespec-client-generator-core/src/interfaces.ts
- packages/typespec-client-generator-core/src/internal-utils.ts
- packages/typespec-client-generator-core/test/decorators/override.test.ts
- packages/typespec-client-generator-core/test/types/built-in-types.test.ts
fix: https://github.com/Azure/typespec-azure/issues/2188
fix: https://github.com/Azure/typespec-azure/issues/2218
> [tcgc] remove useless typing and console log

- .chronus/changes/fix_bugs-2025-1-26-14-49-56.md
- .chronus/changes/fix_bugs-2025-1-26-15-49-39.md
- packages/typespec-client-generator-core/src/example.ts
- packages/typespec-client-generator-core/src/lib.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/examples/example-types.test.ts
- packages/typespec-client-generator-core/test/examples/example-types/getStringFromExtensibleEnum.json
- packages/typespec-client-generator-core/test/types/model-types.test.ts
fix: https://github.com/Azure/typespec-azure/issues/2240
fix: https://github.com/Azure/typespec-azure/issues/2266, issue found by go emitter: https://github.com/Azure/autorest.go/pull/1500#issuecomment-2683816877
> [tcgc] fix known issues

- eng/pipelines/templates/1es-redirect.yml
> Update build tools ref

- .chronus/changes/refine_content_type-2025-1-28-15-46-10.md
- packages/typespec-client-generator-core/src/http.ts
- packages/typespec-client-generator-core/src/package.ts
- packages/typespec-client-generator-core/test/types/bytes-types.test.ts
fix: https://github.com/Azure/typespec-azure/issues/1994
> [tcgc] refine content type related logic

- .chronus/changes/add_page_items_segments-2025-2-4-15-27-53.md
- .chronus/changes/add_page_items_segments-2025-2-4-15-30-24.md
- packages/typespec-client-generator-core/src/http.ts
- packages/typespec-client-generator-core/src/interfaces.ts
- packages/typespec-client-generator-core/src/package.ts
- packages/typespec-client-generator-core/test/packages/paged-operation.test.ts
- packages/typespec-client-generator-core/test/packages/parameters.test.ts
resolve: https://github.com/Azure/typespec-azure/issues/2294
resolve: https://github.com/Azure/typespec-azure/issues/2292
resolve: https://github.com/Azure/typespec-azure/issues/2291
> [tcgc] improvement for paging and body parameter

- .chronus/changes/fix-identifiers-explicit-empty-with-id-2025-2-4-5-18-33.md
- packages/typespec-autorest/src/openapi.ts
- packages/typespec-autorest/test/openapi-output.test.ts
- packages/typespec-azure-resource-manager/src/resource.ts
> Fix using `@identifiers` on array of model with id not respected

- .chronus/changes/remove-projections-2025-2-7-19-30-56.md
- packages/typespec-autorest/src/openapi.ts
- packages/typespec-azure-core/test/test-host.ts
Changes from https://github.com/microsoft/typespec/pull/6327
> Remove reference to projections

- .chronus/config.yaml
- eng/feeds/test/init-templates.e2e.ts
fix https://github.com/microsoft/typespec/issues/6209
> Reenable init templates

- .chronus/changes/fix_next_link_in_header-2025-2-11-17-16-12.md
- packages/typespec-client-generator-core/src/package.ts
- packages/typespec-client-generator-core/test/packages/paged-operation.test.ts
fix: https://github.com/Azure/typespec-azure/issues/2341
> [tcgc] support `@nextLink` along with `@header`

- .chronus/changes/tcgc-fixApiVersions-2025-2-11-13-37-32.md
- packages/typespec-client-generator-core/.vscode/launch.json
- packages/typespec-client-generator-core/src/context.ts
- packages/typespec-client-generator-core/src/interfaces.ts
- packages/typespec-client-generator-core/src/internal-utils.ts
- packages/typespec-client-generator-core/src/package.ts
> [tcgc] maintain superset of api versions for types

- .chronus/changes/discriminated_unions-2025-2-13-15-55-45.md
- packages/typespec-client-generator-core/src/lib.ts
- packages/typespec-client-generator-core/src/types/validate.ts
- packages/typespec-client-generator-core/src/validate.ts
- packages/typespec-client-generator-core/test/types/validate.test.ts
as discussed in dpg office hour, tcgc will help to validate if there is any discriminated unions and report error directly.
> [tcgc] report error for discriminated unions

- .chronus/changes/export_auth_info-2025-2-13-16-9-30.md
- packages/typespec-client-generator-core/src/context.ts
more convenient for emitter to know the exact info of auth.
> [tcgc] output auth related info in the yaml of code model

- eng/feeds/arm/tspconfig.yaml
resolve: https://github.com/Azure/autorest.go/issues/1478
> change generate-examples to generate-samples

- .chronus/changes/rollback_sequence-2025-2-14-14-19-27.md
- packages/typespec-client-generator-core/src/internal-utils.ts
do not break the model sequence. cc: @qiaozha
> [tcgc] Change `listRawSubClients` from DFS to BFS.

- .chronus/changes/azure-http-specs_validate-orphan-model-serializable-2025-2-6-14-48-18.md
- .chronus/changes/change-workspace-ranges-2025-2-6-10-4-22.md
- .chronus/changes/drop-node-18-2025-2-5-1-34-1.md
- .chronus/changes/specs_arm_error-2025-2-4-10-8-15.md
- .chronus/changes/upgrade-deps-march-2025-2025-2-4-22-27-47.md
- packages/azure-http-specs/CHANGELOG.md
- packages/azure-http-specs/package.json
command: `pnpm change version --only "@azure-tools/azure-http-specs"`
> bump azure-http-specs

- .chronus/changes/decorator-override-2025-2-14-15-58-44.md
- packages/typespec-client-generator-core/src/decorators.ts
- packages/typespec-client-generator-core/test/decorators/scope.test.ts
Resolves https://github.com/Azure/typespec-azure/issues/1961
> Specific scope decorator should always override all-scopes decorator

- website/src/content/current-sidebar.ts
- website/src/content/docs/docs/howtos/Generate client libraries/13license.mdx
- website/src/content/docs/docs/libraries/typespec-client-generator-core/guideline.md
- website/src/content/docs/docs/libraries/typespec-client-generator-core/usage.md
resolve: https://github.com/Azure/typespec-azure/issues/2272
> [tcgc] license doc

- .chronus/changes/doc_partly-clean-unsupported-2025-2-20-14-46-53.md
- packages/azure-http-specs/spec-summary.md
- packages/azure-http-specs/specs/azure/example/basic/main.tsp
- website/src/content/docs/docs/getstarted/azure-core/step04.md
- website/src/content/docs/docs/getstarted/azure-core/step10.md
- website/src/content/docs/docs/howtos/ARM/resource-operations.md
- website/src/content/docs/docs/howtos/ARM/resource-type.md
- website/src/content/docs/docs/howtos/Generate client libraries/03convenient.mdx
- website/src/content/docs/docs/howtos/Generate client libraries/04renaming.mdx
- website/src/content/docs/docs/howtos/Generate client libraries/07tcgcTypes.mdx
- website/src/content/docs/docs/howtos/Generate client libraries/10longRunningOperations.mdx
- website/src/content/docs/docs/libraries/azure-core/rules/no-openapi.md
- website/src/content/docs/docs/libraries/azure-resource-manager/rules/arm-resource-provisioning-state.md
- website/src/content/docs/docs/migrate-swagger/checklists/migrate-dp-tips.md
> doc, partly clean unsupported/deprecated tsp from documents

- .chronus/changes/fix_corner_issue-2025-2-25-14-27-8.md
- packages/typespec-client-generator-core/src/example.ts
- packages/typespec-client-generator-core/src/interfaces.ts
- packages/typespec-client-generator-core/src/internal-utils.ts
- packages/typespec-client-generator-core/src/public-utils.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/public-utils/get-generated-name.test.ts
- packages/typespec-client-generator-core/test/test-host.ts
- packages/typespec-client-generator-core/test/types/model.test.ts
fix: https://github.com/Azure/typespec-azure/issues/2385
> [tcgc] resolve generated name for anonymous model conflict with user-defined type name

- .chronus/changes/tcgc-remove-old-multipart-2025-2-19-17-3-27.md
- packages/typespec-client-generator-core/src/lib.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/methods/spread.test.ts
- packages/typespec-client-generator-core/test/public-utils/get-http-operation-parameter.test.ts
- packages/typespec-client-generator-core/test/types/multipart.test.ts
fix https://github.com/Azure/typespec-azure/issues/2398
> [TCGC] remove support for old multipart

- .chronus/changes/fix-multipart-doc-autorest-2025-2-27-8-21-2.md
- packages/typespec-autorest/src/openapi.ts
- packages/typespec-autorest/test/multipart.test.ts
fix #2458
Same fix as what done for openapi3 here https://github.com/microsoft/typespec/pull/6559/
> Fixing multipart doc for autorest

- .chronus/changes/tcgc-overrideWithSubsetOfParams-2025-2-26-12-15-8.md
- packages/typespec-client-generator-core/src/decorators.ts
- packages/typespec-client-generator-core/src/http.ts
- packages/typespec-client-generator-core/src/lib.ts
- packages/typespec-client-generator-core/test/decorators/override.test.ts
> [tcgc] override with subset of params

- .chronus/changes/remove_deprecation-2025-2-27-11-50-40.md
- packages/typespec-client-generator-core/src/example.ts
- packages/typespec-client-generator-core/src/http.ts
- packages/typespec-client-generator-core/src/interfaces.ts
- packages/typespec-client-generator-core/src/package.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/clients/params.test.ts
- packages/typespec-client-generator-core/test/clients/structure.test.ts
- packages/typespec-client-generator-core/test/decorators/api-version.test.ts
- packages/typespec-client-generator-core/test/decorators/client-initialization.test.ts
- packages/typespec-client-generator-core/test/decorators/client-namespace.test.ts
- packages/typespec-client-generator-core/test/decorators/client.test.ts
- packages/typespec-client-generator-core/test/examples/load.test.ts
- packages/typespec-client-generator-core/test/methods/lro.test.ts
- packages/typespec-client-generator-core/test/methods/parameters.test.ts
- packages/typespec-client-generator-core/test/methods/spread.test.ts
- packages/typespec-client-generator-core/test/packages/azure-widget-service.test.ts
- packages/typespec-client-generator-core/test/packages/versioning.test.ts
- packages/typespec-client-generator-core/test/public-utils/get-cross-language-definition-id.test.ts
- packages/typespec-client-generator-core/test/public-utils/get-http-operation-parameter.test.ts
- packages/typespec-client-generator-core/test/types/model.test.ts
- packages/typespec-client-generator-core/test/types/multipart.test.ts
- packages/typespec-client-generator-core/test/utils.ts
resolve: https://github.com/Azure/typespec-azure/issues/2451
> [tcgc] remove deprecated things

- .gitignore
- pnpm-lock.yaml
Dedicated pr to double check there is no issues this time
core pr https://github.com/microsoft/typespec/pull/6733
> Uptake esbuild bundler changes

- .chronus/changes/tcgc-responseAsBoolDecorator-2025-2-28-14-25-58.md
- packages/typespec-client-generator-core/README.md
- packages/typespec-client-generator-core/generated-defs/Azure.ClientGenerator.Core.ts
- packages/typespec-client-generator-core/lib/decorators.tsp
- packages/typespec-client-generator-core/src/decorators.ts
- packages/typespec-client-generator-core/src/http.ts
- packages/typespec-client-generator-core/src/lib.ts
- packages/typespec-client-generator-core/src/package.ts
- packages/typespec-client-generator-core/src/tsp-index.ts
- packages/typespec-client-generator-core/test/decorators/response-as-bool.test.ts
- website/src/content/docs/docs/libraries/typespec-client-generator-core/reference/decorators.md
- website/src/content/docs/docs/libraries/typespec-client-generator-core/reference/index.mdx
> [tcgc] add `@responseAsBool` decorator

- .chronus/changes/ease-enforce-constraing-for-custom-resources-2025-2-28-16-24-54.md
- packages/typespec-azure-resource-manager/src/private.decorators.ts
- packages/typespec-azure-resource-manager/src/rules/arm-custom-resource-usage-discourage.ts
- packages/typespec-azure-resource-manager/test/enforce-constraint.test.ts
- packages/typespec-azure-resource-manager/test/rules/arm-custom-resource-usage-discourage.test.ts
issue: https://github.com/Azure/typespec-azure/issues/2386
> Ease enforce constraint for custom resources identified with `@legacy.armCustomResource` decorator

- .chronus/changes/fix_anonymous-2025-3-1-18-39-9.md
- packages/typespec-client-generator-core/src/public-utils.ts
- packages/typespec-client-generator-core/test/public-utils/get-generated-name.test.ts
fix: https://github.com/Azure/typespec-azure/issues/1713
> [tcgc] consider method parameter model when generating name for anonymous model

- .chronus/changes/spector-parameterizedNextLink-2025-3-4-17-16-16.md
- packages/azure-http-specs/specs/azure/core/page/main.tsp
- packages/azure-http-specs/specs/azure/core/page/mockapi.ts
> [spector] add test for `Azure.Core.Legacy.parameterizedNextLink`

- .chronus/changes/fix-old-link-2025-3-9-15-56-50.md
- packages/samples/test/output/azure/core/data-plane/api-path-parameter/@azure-tools/typespec-autorest/2022-08-31/openapi.json
- packages/samples/test/output/azure/core/data-plane/api-path-parameter/@typespec/openapi3/openapi.2022-08-31.yaml
- packages/samples/test/output/azure/core/data-plane/custom-error-type/@azure-tools/typespec-autorest/2022-08-31/openapi.json
- packages/samples/test/output/azure/core/data-plane/custom-error-type/@typespec/openapi3/openapi.2022-08-31.yaml
- packages/samples/test/output/azure/core/data-plane/trait-versioning/@azure-tools/typespec-autorest/2022-08-31/openapi.json
- packages/samples/test/output/azure/core/data-plane/trait-versioning/@azure-tools/typespec-autorest/2023-02-07/openapi.json
- packages/samples/test/output/azure/core/data-plane/trait-versioning/@typespec/openapi3/openapi.2022-08-31.yaml
- packages/samples/test/output/azure/core/data-plane/trait-versioning/@typespec/openapi3/openapi.2023-02-07.yaml
- packages/samples/test/output/azure/core/data-plane/widget-manager/@azure-tools/typespec-autorest/2022-08-31/openapi.json
- packages/samples/test/output/azure/core/data-plane/widget-manager/@typespec/openapi3/openapi.2022-08-31.yaml
- packages/typespec-azure-core/lib/foundations.tsp
- website/src/content/docs/docs/libraries/azure-core/reference/data-types.md
issue: https://github.com/microsoft/typespec/issues/5692
> Update documentation link for inner error

- .chronus/changes/tcgc-fixClientNamespaceOverride-2025-3-9-17-56-49.md
- packages/typespec-client-generator-core/src/decorators.ts
- packages/typespec-client-generator-core/test/package/namespaces.test.ts
> [tcgc] fix clientNamespace bug when used earlier in namespace path

- .chronus/changes/fix-client-initiailization-test-2025-3-14-14-27-46.md
- packages/azure-http-specs/spec-summary.md
- packages/azure-http-specs/specs/azure/client-generator-core/client-initialization/client.tsp
> [azure-http-specs] fix client initialization spec problem

- .chronus/changes/azure_http_specs_fix_finalresult_arm-2025-3-11-17-52-30.md
- packages/azure-http-specs/specs/azure/resource-manager/operation-templates/lro.tsp
Issue discussed: https://github.com/Azure/azure-rest-api-specs/pull/33875#discussion_r2038793485
> azure-http-specs ARM, fix FinalResult for LRO POST

- .chronus/changes/spector-addDeserializeEmptyStringAsNullTest-2025-4-14-23-16-16.md
- packages/azure-http-specs/spec-summary.md
- packages/azure-http-specs/specs/azure/client-generator-core/deserialize-empty-string-as-null/main.tsp
- packages/azure-http-specs/specs/azure/client-generator-core/deserialize-empty-string-as-null/mockapi.ts
add spec test for decorator `@deserializeEmptyStringAsNull`
> [spector] add test for decorator deserializeEmptyStringAsNull.

- .chronus/changes/no-magic-typekit-2025-3-18-10-14-26.md
- packages/typespec-autorest-canonical/README.md
- packages/typespec-autorest/README.md
- packages/typespec-autorest/src/openapi.ts
- packages/typespec-client-generator-core/README.md
- packages/typespec-client-generator-core/src/clients.ts
- packages/typespec-client-generator-core/src/http.ts
- packages/typespec-client-generator-core/src/internal-utils.ts
- packages/typespec-client-generator-core/src/methods.ts
- pnpm-lock.yaml
- website/src/content/docs/docs/emitters/typespec-autorest-canonical/reference/emitter.md
- website/src/content/docs/docs/emitters/typespec-autorest/reference/emitter.md
- website/src/content/docs/docs/libraries/typespec-client-generator-core/reference/emitter.md
Depends on https://github.com/microsoft/typespec/pull/7018/
> Use instantiated Typekits instead of default typekit

- eng/feeds/__snapshots__/azure-core/tspconfig.yaml
- eng/feeds/__snapshots__/azure-core_stand_alone/tspconfig.yaml
- eng/feeds/arm/tspconfig.yaml
- eng/feeds/data-plane/tspconfig.yaml
- eng/feeds/data-plane/tspconfig_stand_alone.yaml
related issue: https://github.com/Azure/autorest.typescript/issues/3067
> Update tspconfig options with kebab-case style for JS emitter

- website/src/components/playground-component/import-map.ts
- website/src/components/playground-component/playground.tsx
Same pr as core https://github.com/microsoft/typespec/pull/6798
> Load older version playground

- .chronus/changes/tk-is-assignable-2025-3-24-10-53-16.md
- packages/typespec-autorest/src/openapi.ts
- packages/typespec-client-generator-core/src/http.ts
Depends on https://github.com/microsoft/typespec/pull/7106
> migrate checker.isTypeAssignableTo to $.type.isAssignableTo

- .chronus/changes/tk-intrinsic-getters-2025-3-24-15-47-1.md
- packages/typespec-azure-core/src/decorators.ts
- packages/typespec-azure-core/src/lro-helpers.ts
- packages/typespec-azure-core/src/lro-info.ts
Depends on https://github.com/microsoft/typespec/pull/7125
> switch to typekit for intrinsic types

- .chronus/changes/fix-unsupported-param-target-prop-2025-3-29-22-29-6.md
- packages/typespec-autorest/src/openapi.ts
- packages/typespec-autorest/test/parameters.test.ts
fix https://github.com/microsoft/typespec/issues/6110 take 2, added a test this time, seems like it was just a minor missed change in the previous pr, maybe a cmd+z issue
> Fix unsupported param type target

- eng/feeds/__snapshots__/azure-core/tspconfig.yaml
- eng/feeds/__snapshots__/azure-core_stand_alone/tspconfig.yaml
- eng/feeds/arm/tspconfig.yaml
- eng/feeds/data-plane/tspconfig.yaml
- eng/feeds/data-plane/tspconfig_stand_alone.yaml
> [python] update tspconfigs with `namespace` switch

- .chronus/changes/uptake-patch-optionality-change-2025-4-6-8-42-33.md
- packages/samples/test/output/core/init/@azure-tools/typespec-autorest/openapi.json
- packages/samples/test/output/core/visibility/@azure-tools/typespec-autorest/openapi.json
- packages/typespec-azure-core/lib/operations.tsp
- pnpm-lock.yaml
Core https://github.com/microsoft/typespec/pull/7230
> Uptake patch optionality change

- .chronus/changes/tcgc-cache_array_map-2025-4-6-18-37-49.md
- .chronus/changes/tcgc-individual-none-2025-3-27-5-13-0.md
- packages/typespec-client-generator-core/CHANGELOG.md
- packages/typespec-client-generator-core/package.json
- packages/typespec-client-generator-core/src/http.ts
- packages/typespec-client-generator-core/src/internal-utils.ts
- packages/typespec-client-generator-core/src/methods.ts
- packages/typespec-client-generator-core/test/methods/paged-operation.test.ts
1. fix 0.55.1 not backmerged to main
2. make array and dictionary type as referenced type
3. change initialized by default
fix https://github.com/Azure/typespec-azure/issues/2638
> bump tcgc 0.56.1

- .chronus/changes/tcgc-fix_issues-2025-4-9-12-51-56.md
- .chronus/changes/tcgc-fix_issues-2025-4-9-13-6-49.md
- packages/typespec-client-generator-core/src/example.ts
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/examples/http-operation-examples.test.ts
- packages/typespec-client-generator-core/test/examples/http-operation-examples/bodyFallbackClientName.json
- packages/typespec-client-generator-core/test/types/array.test.ts
- packages/typespec-client-generator-core/test/types/dictionary.test.ts
fix: https://github.com/Azure/typespec-azure/issues/2650
fix missing logic of: https://github.com/Azure/typespec-azure/issues/2595
> [tcgc] fix issues found by release

- .chronus/changes/tcgc-lintAgainstMultipleParamAlias-2025-4-12-12-45-13.md
- packages/typespec-client-generator-core/src/decorators.ts
- packages/typespec-client-generator-core/src/lib.ts
- packages/typespec-client-generator-core/test/decorators/param-alias.test.ts
> [tcgc] add linter warning for multiple param aliases

- .chronus/changes/tcgc-rollbackNodeCheckRelease-2025-4-12-15-11-55.md
- packages/typespec-client-generator-core/src/http.ts
- packages/typespec-client-generator-core/src/internal-utils.ts
- packages/typespec-client-generator-core/src/methods.ts
> [tcgc] rollback node check release

- .chronus/changes/azhang_ExtensionActionScope-2025-4-2-12-37-46.md
- packages/samples/specs/resource-manager/operations/operation-provider/main.tsp
- packages/samples/test/output/azure/resource-manager/operations/operation-provider/@azure-tools/typespec-autorest/2022-11-01-preview/openapi.json
- packages/typespec-azure-resource-manager/lib/operations.tsp
- packages/typespec-azure-resource-manager/lib/parameters.tsp
- website/src/content/docs/docs/libraries/azure-resource-manager/reference/data-types.md
- website/src/content/docs/docs/libraries/azure-resource-manager/reference/index.mdx
- website/src/content/docs/docs/libraries/azure-resource-manager/reference/interfaces.md
> Adding ExtensionResourceActionScope for ARMProviderAction operation template

- .chronus/changes/fix-incorrect-privatelink-definition-2025-4-8-17-2-44.md
- packages/typespec-autorest/test/arm/arm.test.ts
- packages/typespec-azure-resource-manager/lib/common-types/private-links-ref.tsp
issues: 
- https://github.com/Azure/typespec-azure/issues/2636
- https://github.com/Azure/typespec-azure/issues/2637
> Fix PrivateLinkResourceListResultV5 and PrivateEndpointConnectionListResultV5

- .chronus/changes/try_fix_singleton-2025-4-14-15-55-23.md
- packages/typespec-azure-resource-manager/src/namespace.ts
- packages/typespec-azure-resource-manager/test/namespace.test.ts
- packages/typespec-azure-resource-manager/test/test-host.ts
fix: https://github.com/Azure/typespec-azure/issues/1374
> [arm lib] fix singleton resource autoroute issue

- .chronus/changes/fix-addition-info-type-2025-4-22-13-26-52.md
- .chronus/changes/fix-addition-info-type-2025-4-22-13-45-19.md
- packages/samples/common-types/gen.ts
- packages/typespec-azure-resource-manager/lib/common-types/types.tsp
- website/src/content/docs/docs/libraries/azure-resource-manager/reference/data-types.md
issue: https://github.com/Azure/typespec-azure/issues/2657
> ErrorAdditionalInfo.info should be unknown 

- .chronus/changes/try_fix_singleton-2025-4-14-15-55-23.md
- packages/typespec-azure-resource-manager/src/namespace.ts
- packages/typespec-azure-resource-manager/test/namespace.test.ts
- packages/typespec-azure-resource-manager/test/test-host.ts
fix: https://github.com/Azure/typespec-azure/issues/1374
> [arm lib] fix singleton resource autoroute issue (#2672)

- .chronus/changes/azure-reinjection-2025-5-26-16-41-32.md
- packages/typespec-azure-core/src/decorators.ts
- packages/typespec-client-generator-core/test/methods/paged-operation.test.ts
1. add test to repro the mutator issue.
2. add changeset for core lib to mitigate the nightly build issue.
> [tcgc] add versioning test for reinjection

- .chronus/changes/foreign-resource-2025-4-29-16-48-49.md
- packages/typespec-azure-resource-manager/src/private.decorators.ts
- packages/typespec-azure-resource-manager/src/resource.ts
- packages/typespec-azure-resource-manager/src/rules/arm-resource-invalid-envelope-property.ts
- packages/typespec-azure-resource-manager/test/resource.test.ts
> Add support for partial resources 

- website/src/content/current-sidebar.ts
- website/src/content/docs/docs/emitters/clients/typespec-python/reference/emitter.md
- website/src/content/docs/docs/emitters/clients/typespec-python/reference/index.mdx
part of https://github.com/Azure/typespec-azure/issues/2693
> [doc] add python emitter doc

- website/src/content/current-sidebar.ts
- website/src/content/docs/docs/emitters/clients/typespec-ts/reference/emitter.md
- website/src/content/docs/docs/emitters/clients/typespec-ts/reference/index.mdx
part of https://github.com/Azure/typespec-azure/issues/2693
> add-docs-for-js-client-emitter

- pnpm-lock.yaml
Followup to https://github.com/microsoft/typespec/pull/7593
> update deps and regenerate pnpm-lock

- eng/pipelines/templates/1es-redirect.yml
- eng/pipelines/templates/variables/image.yml
- eng/scripts/gen-sdk.js
Related: https://github.com/microsoft/typespec/pull/7399
> [EngSys] Update pipelines to ubuntu-24.04 and azsdk-pool

- .chronus/changes/fix_usage-2025-5-18-11-26-28.md
- packages/typespec-client-generator-core/src/types.ts
- packages/typespec-client-generator-core/test/decorators/usage.test.ts
fix: https://github.com/Azure/typespec-azure/issues/2860
> Fix `disableUsageAccessPropagationToBase` issue for discriminated model

- .chronus/changes/fix-scope-2025-5-20-10-56-25.md
- packages/typespec-client-generator-core/src/decorators.ts
- packages/typespec-client-generator-core/test/decorators/scope.test.ts
fix: https://github.com/Azure/typespec-azure/issues/2870
> [TCGC] Fix scope calculation logic

- .chronus/changes/client_name_validation-2025-5-23-16-12-20.md
- packages/typespec-client-generator-core/src/cache.ts
- packages/typespec-client-generator-core/src/internal-utils.ts
- packages/typespec-client-generator-core/src/validations/types.ts
- packages/typespec-client-generator-core/test/validations/types.test.ts
fix: https://github.com/Azure/typespec-azure/issues/2885
> [TCGC] Consider `@clientLocation` when validate client name collision

- website/src/content/docs/docs/howtos/ARM/versioning.md
> Add FAQ for changing `@pattern`

- pnpm-lock.yaml
Important is upgrade of pbkdf2 to fix vulnerability
> Upagrade lock file

- eng/pipelines/ci.yml
Handle regression in node 24.4. Our issue trascking it https://github.com/microsoft/typespec/issues/7861
> Pin node 24.3

- website/src/content/docs/docs/howtos/Generate client libraries/02package.mdx
- website/src/content/docs/docs/howtos/Generate client libraries/03client.mdx
Mostly for adding generated code (in additional to usage).
> java, update Howtos doc for Client

- packages/typespec-client-generator-core/test/methods/paged-operation.test.ts
Fix: https://github.com/Azure/typespec-azure/issues/2287
> [TCGC] Add test for nested paging cases

- .chronus/changes/fix_alternate_type-2025-6-17-16-38-22.md
- packages/typespec-client-generator-core/src/decorators.ts
- packages/typespec-client-generator-core/test/decorators/alternate-type.test.ts
Fix: https://github.com/Azure/typespec-azure/issues/2986
> [TCGC] Fix typing inconsistent when using `@alternateType` along with `@override`

- website/src/content/docs/docs/emitters/clients/typespec-ts/reference/emitter.md
This PR is trying to add some option descriptions for typespec-ts emitter
> Update typespec-ts docs

- .chronus/changes/no-common-types-alias-internal-2025-6-21-23-24-20.md
- packages/typespec-azure-resource-manager/lib/Legacy/interfaces.tsp
- packages/typespec-azure-resource-manager/lib/foundations/arm.foundations.tsp
- packages/typespec-azure-resource-manager/lib/interfaces.tsp
- packages/typespec-azure-resource-manager/lib/operations.tsp
- website/src/content/docs/docs/libraries/azure-resource-manager/reference/data-types.md
> Do not use common types aliases internally (ARM)

- .chronus/changes/fix_paging-2025-6-28-16-10-17.md
- packages/typespec-client-generator-core/src/methods.ts
- packages/typespec-client-generator-core/test/methods/paged-operation.test.ts
fix: https://github.com/Azure/typespec-azure/issues/3069
> [TCGC] Find the correct first segment before doing page segments mapping.

- .chronus/changes/tcgc-pageSizeParameter-2025-7-26-14-33-36.md
- packages/typespec-client-generator-core/src/interfaces.ts
- packages/typespec-client-generator-core/src/methods.ts
- packages/typespec-client-generator-core/test/methods/paged-operation.test.ts
> [tcgc] add `.pageSizeParameter` to paging metadata

- .chronus/changes/upgrade-deps-aug-2025-2025-7-28-20-0-13.md
- package.json
- packages/azure-http-specs/package.json
- packages/e2e-tests/package.json
- packages/integration-tester/package.json
- packages/samples/package.json
- packages/typespec-autorest-canonical/package.json
- packages/typespec-autorest/package.json
- packages/typespec-azure-core/package.json
- packages/typespec-azure-playground-website/package.json
- packages/typespec-azure-portal-core/package.json
- packages/typespec-azure-resource-manager/package.json
- packages/typespec-azure-rulesets/package.json
- packages/typespec-azure-vscode/package.json
- packages/typespec-client-generator-core/package.json
- pnpm-lock.yaml
- website/package.json
Core pr https://github.com/microsoft/typespec/pull/8317
> Upgrade dependencies august 2025

- .chronus/changes/namespace-spec-fix-2025-7-29-12-9-11.md
- packages/azure-http-specs/specs/client/namespace/client.tsp
https://github.com/Azure/typespec-azure/pull/1929#discussion_r2310882738
> remove language scoping for client namespace spec

- .chronus/changes/tcgc-multipleResponses-2025-7-28-17-29-3.md
- packages/typespec-client-generator-core/src/http.ts
- packages/typespec-client-generator-core/src/lib.ts
- packages/typespec-client-generator-core/test/methods/responses.test.ts
> [tcgc] return union for multiple responses

- .chronus/changes/tcgc-flattenPropertyLegacy-2025-7-27-12-12-36.md
- .chronus/changes/tcgc-flattenPropertyLegacy-2025-7-27-12-12-6.md
- .chronus/changes/tcgc-flattenPropertyLegacy-2025-7-27-14-6-8.md
- packages/azure-http-specs/specs/azure/client-generator-core/flatten-property/main.tsp
- packages/typespec-autorest/test/flatten.test.ts
- packages/typespec-client-generator-core/README.md
- packages/typespec-client-generator-core/generated-defs/Azure.ClientGenerator.Core.Legacy.ts
- packages/typespec-client-generator-core/generated-defs/Azure.ClientGenerator.Core.ts
- packages/typespec-client-generator-core/lib/decorators.tsp
- packages/typespec-client-generator-core/lib/legacy.tsp
- packages/typespec-client-generator-core/src/decorators.ts
- packages/typespec-client-generator-core/src/tsp-index.ts
- packages/typespec-client-generator-core/test/decorators/flatten-property.test.ts
- website/src/content/docs/docs/libraries/typespec-client-generator-core/reference/decorators.md
- website/src/content/docs/docs/libraries/typespec-client-generator-core/reference/index.mdx
> [tcgc] move `@flattenProperty` to legacy namespace

- .chronus/changes/azure-http-specs_namespace-for-java-2025-8-17-10-11-53.md
- packages/azure-http-specs/specs/azure/versioning/previewVersion/main.tsp
> azure-http-specs, consistency for namespace on java

- .chronus/changes/fix_api_version-2025-8-30-11-42-41.md
- packages/typespec-client-generator-core/src/context.ts
- packages/typespec-client-generator-core/src/lib.ts
- packages/typespec-client-generator-core/test/package/versioning.test.ts
Fix: https://github.com/Azure/typespec-azure/issues/3352
> [TCGC] Handle wrong `api-version` config.
